name: mundodaspalavras
description: "Aplicação Flutter educativa de jogos sérios para alfabetização infantil."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Dependências do Flutter
  logger: ^1.2.0

  # UI e Icons
  cupertino_icons: ^1.0.8

  # Resposividade da aplicação
  flutter_screenutil: ^5.9.0

  # Lotiie para animações pré-renderizadas
  lottie: ^2.7.0  

  # Armazenamento local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # gráficos
  fl_chart: ^0.64.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Geração automática dos Hive adapters
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
#configuração de animações a usar
    - assets/animations/loading.json
    - assets/animations/coffeties.json
    - assets/animations/conquest.json
    - assets/animations/progression_stars.json

#configuração de imagens a usar
    - assets/images/background_game_menu.png
    - assets/images/pencils.png
    - assets/images/sun_cloud.png

# Configuração de fontes a usar
  fonts:
    - family: ComicNeue                     # tipo de letra Comic Sans, para jogos de pré-escolar e interface geral
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf

    - family: Cursive                         # tipo de letra manuscrita, para joogos de 1º cilco
      fonts:
        - asset: assets/fonts/Cursive-Regular.ttf

    - family: Slabo                           # tipo de letra máquina, para joogos de 1º cilco
      fonts:
        - asset: assets/fonts/Slabo-Regular.ttf