name: mundodaspalavras
description: "Aplicação Flutter educativa de jogos sérios para alfabetização infantil."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI e Icons
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0

  # Armazenamento local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Geração automática dos Hive adapters
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # Ativa assets (se tiveres imagens ou fontes)
  # assets:
  #   - assets/images/
  #   - assets/sounds/

  # Exemplo se usares fontes personalizadas:
  # fonts:
  #   - family: FredokaOne
  #     fonts:
  #       - asset: assets/fonts/FredokaOne-Regular.ttf
