name: mundodaspalavras
description: "Aplicação Flutter educativa de jogos sérios para alfabetização infantil."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Logging
  logger: ^1.2.0

  # UI e Responsividade
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  lottie: ^3.3.1

  # Sons
  audioplayers: ^5.2.1

  # Persistência
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

  # Gráficos
  fl_chart: ^0.60.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    # Animações
    - assets/animations/loading.json
    - assets/animations/coffeties.json
    - assets/animations/conquest.json
    - assets/animations/one_star.json
    - assets/animations/two_star.json
    - assets/animations/tree_star.json
    - assets/animations/check.json

    # Sons
    - assets/sounds/conquest.wav
    - assets/sounds/correct.wav
    - assets/sounds/intro_music.mp3
    - assets/sounds/level_up.wav
    - assets/sounds/wrong.wav

    # Imagens gerais
    - assets/images/sun.png

    # Imagens dos stickers
    - assets/stickers/monkey.jpg
    - assets/stickers/elephant.jpg

  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf

    - family: Cursive
      fonts:
        - asset: assets/fonts/Cursive-Regular.ttf

    - family: Slabo
      fonts:
        - asset: assets/fonts/Slabo-Regular.ttf
