name: mundodaspalavras
description: "Aplicação Flutter educativa de jogos sérios para alfabetização infantil."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  svg_path_parser: ^1.1.2
  bloc: ^9.0.0

  # Logger
  logger: ^1.2.0

  # UI e Icons
  cupertino_icons: ^1.0.8

  # Responsividade da aplicação
  flutter_screenutil: ^5.9.0

  # Lottie para animações pré‑renderizadas
  lottie: ^3.3.1  

  # Efeitos sonoros
  audioplayers: ^5.2.1

  # Efeitos vídeo
  video_player: ^2.5.0

  # Armazenamento local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Gráficos
  fl_chart: 0.71.0


dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner:  ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    # Animações
    - assets/animations/

    # Sons gerais
    - assets/sounds/
    - assets/sounds/animations/
    - assets/sounds/characters/
    - assets/sounds/words/
    - assets/sounds/games/
    # Imagens gerais
    - assets/images/
    - assets/images/words/
    - assets/images/games/

    # Tutoriais
    - assets/tutorials/
    - assets/tutorials/count_syllables_fixed.mp4

    # Imagens dos pontos de controle de letras e números
    - assets/phontics_assets_points/

    # Jogo 2 
    - assets/phontics_assets_points/pt_phonetics/
    - assets/phontics_assets_points/pt_upper_phonetics/
    - assets/phontics_assets_points/cursiveLower/
    - assets/phontics_assets_points/cursiveUpper/
    - assets/phontics_assets_points/numbers_phontics/
    
  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf

    - family: Cursive
      fonts:
        - asset: assets/fonts/Cursive-Regular.ttf

    - family: CursiveDotted
      fonts:
        - asset: assets/fonts/Cursive-Dotted.ttf

    - family: Slabo
      fonts:
        - asset: assets/fonts/Slabo-Regular.ttf


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/PD_icon.webp"
  min_sdk_android: 21