name: mundodaspalavras
description: "Aplicação Flutter educativa de jogos sérios para alfabetização infantil."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Logger
  logger: ^1.2.0

  # UI e Icons
  cupertino_icons: ^1.0.8

  # Responsividade da aplicação
  flutter_screenutil: ^5.9.0

  # Lottie para animações pré‑renderizadas
  lottie: ^3.3.1  

  # Efeitos sonoros
  audioplayers: ^5.2.1

  # Armazenamento local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Gráficos
  fl_chart: 0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner:  ^2.4.7
  svg_path_parser: ^1.0.0
  flutter_bloc: ^8.1.0

flutter:
  uses-material-design: true

  assets:
    # Animações
    - assets/animations/

    # Sons gerais
    - assets/sounds/
    - assets/sounds/animations/
    - assets/sounds/characters_sounds/
    - assets/sounds/games/
    # Imagens gerais
    - assets/images/
    - assets/images/words/
    - assets/images/games/

    # Imagens dos pontos de controle de letras e números
    - assets/phontics_assets_points/

  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf

    - family: Cursive
      fonts:
        - asset: assets/fonts/Cursive-Regular.ttf

    - family: Slabo
      fonts:
        - asset: assets/fonts/Slabo-Regular.ttf