name: mundodaspalavras
description: "Aplicação Flutter educativa de jogos sérios para alfabetização infantil."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  svg_path_parser: ^1.1.2
  bloc: ^9.0.0

  # Logger
  logger: ^1.2.0

  # UI e Icons
  cupertino_icons: ^1.0.8

  # Responsividade da aplicação
  flutter_screenutil: ^5.9.0

  # Lottie para animações pré‑renderizadas
  lottie: ^3.3.1  

  # Efeitos sonoros
  audioplayers: ^5.2.1

  # Armazenamento local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Gráficos
  fl_chart: 0.71.0


dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner:  ^2.4.7

flutter:
  uses-material-design: true

  assets:
    # Animações
    - assets/animations/

    # Sons gerais
    - assets/sounds/
    - assets/sounds/animations/
    - assets/sounds/characters_sounds/
    - assets/sounds/games/
    # Imagens gerais
    - assets/images/
    - assets/images/words/
    - assets/images/games/

    # Imagens dos pontos de controle de letras e números
    - assets/phontics_assets_points/


# // lower pt

    - assets/phontics_assets_points/pt_phontics/d_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/f_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/b_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/j_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/l_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/h_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/u_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/A_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/b_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/C_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/e_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/f_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/g_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/h_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/i_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/j_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/l_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/M_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/n_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/N_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/p_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/q_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/R_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/S_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/t_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/u_lower_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/v_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/x_PointsInfo.json
    - assets/phontics_assets_points/pt_phontics/z_PointsInfo.json

# /// upper pt
    - assets/phontics_assets_points/pt_upper_phonetics/A_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/B_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/D_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/E_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/F_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/G_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/H_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/i_lowercase_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/I_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/J_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/L_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/M_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/O_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/p_lowercase_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/P_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/Q_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/R_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/T_PointsInfo.json
    - assets/phontics_assets_points/pt_upper_phonetics/U_PointsInfo.json

# /// numbers
    - assets/phontics_assets_points/numbers_phontics/0_PointsInfo.json
    - assets/phontics_assets_points/numbers_phontics/1_PointsInfo.json
    - assets/phontics_assets_points/numbers_phontics/2_PointsInfo.json
    - assets/phontics_assets_points/numbers_phontics/3_PointsInfo.json
    - assets/phontics_assets_points/numbers_phontics/4_PointsInfo.json
    - assets/phontics_assets_points/numbers_phontics/5_PointsInfo.json
    - assets/phontics_assets_points/numbers_phontics/6_PointsInfo.json
    - assets/phontics_assets_points/numbers_phontics/7_PointsInfo.json
    - assets/phontics_assets_points/numbers_phontics/8_PointsInfo.json
    - assets/phontics_assets_points/numbers_phontics/9_PointsInfo.json



  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf

    - family: Cursive
      fonts:
        - asset: assets/fonts/Cursive-Regular.ttf

    - family: Slabo
      fonts:
        - asset: assets/fonts/Slabo-Regular.ttf