name: mundodaspalavras
description: "Aplicação Flutter educativa de jogos sérios para alfabetização infantil."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI e Icons
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0

  # Armazenamento local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Geração automática dos Hive adapters
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  # Configuração de fontes a usar
  fonts:
    - family: ComicNeue      # tipo de letra Comic Sans, para jogos de pré-escolar e interface geral
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
    - family: Cursive  # tipo de letra manuscrita, para joogos de 1º cilco
      fonts:
        - asset: assets/fonts/Cursive-Regular.ttf
    - family: Slabo       # tipo de letra máquina, para joogos de 1º cilco
      fonts:
        - asset: assets/fonts/Slabo-Regular.ttf


