import 'package:hive/hive.dart';
part 'word_model.g.dart';

@HiveType(typeId: 2)
class WordModel extends HiveObject {
  @HiveField(0)
  String text;

  @HiveField(1)
  String newLetter;

  @HiveField(2)
  String topic;

  @HiveField(3)
  String difficulty;

  @HiveField(4)
  List<String> syllables;

  @HiveField(5)
  int syllableCount;

  @HiveField(6)
  String? audioFileName; // exceção manual para casos de nomes com acentuação, caractéres especiais ou espaços

  @HiveField(7)
  String? imageFileName; // exceção manual para casos de nomes com acentuação, caractéres especiais ou espaços

  WordModel({
    required this.text,
    required this.newLetter,
    required this.topic,
    required this.difficulty,
    required this.syllables,
    required this.syllableCount,
    this.audioFileName,
    this.imageFileName,
  });

  String get audioPath => audioFileName ?? text;
  String get imagePath => 'assets/images/words/${imageFileName ?? text}.webp';
}

Future<void> populateWordsIfNeeded(List<WordModel> words) async {
  final box = await Hive.openBox<WordModel>('words');

  if (box.isEmpty) {
    for (final word in words) {
      await box.add(word);
    }
  }
}

final List<WordModel> words = [
  WordModel(
    text: 'pia',
    newLetter: 'p',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['pia'],
    syllableCount: 1,
  ),
  WordModel(
    text: 'piu',
    newLetter: 'p',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['piu'],
    syllableCount: 1,
  ),
  WordModel(
    text: 'pato',
    newLetter: 't',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['pa', 'to'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'tatu',
    newLetter: 't',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ta', 'tu'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'lã',
    newLetter: 'l',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['lã'],
    syllableCount: 1,
    audioFileName: 'la',
    imageFileName: 'la',
  ),
  WordModel(
    text: 'leão',
    newLetter: 'l',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['le', 'ão'],
    syllableCount: 2,
    audioFileName: 'leao',
    imageFileName: 'leao',
  ),
  WordModel(
    text: 'lula',
    newLetter: 'l',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['lu', 'la'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'lapa',
    newLetter: 'l',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['la', 'pa'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'mia',
    newLetter: 'm',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['mia'],
    syllableCount: 1,
  ),
  WordModel(
    text: 'puma',
    newLetter: 'm',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['pu', 'ma'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'lama',
    newLetter: 'm',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['la', 'ma'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'vaca',
    newLetter: 'v',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['va', 'ca'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'pavão',
    newLetter: 'v',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['pa', 'vão'],
    syllableCount: 2,
    audioFileName: 'pavao',
    imageFileName: 'pavao',
  ),
  WordModel(
    text: 'veado',
    newLetter: 'v',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ve', 'a', 'do'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'cão',
    newLetter: 'c',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['cão'],
    syllableCount: 1,
    audioFileName: 'cao',
    imageFileName: 'cao',
  ),
  WordModel(
    text: 'cuco',
    newLetter: 'c',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['cu', 'co'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'macaco',
    newLetter: 'c',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ma', 'ca', 'co'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'cavalo',
    newLetter: 'c',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ca', 'va', 'lo'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'camelo',
    newLetter: 'c',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ca', 'me', 'lo'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'camaleão',
    newLetter: 'c',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ca', 'ma', 'le', 'ão'],
    syllableCount: 4,
    audioFileName: 'camaleao',
    imageFileName: 'camaleao',
  ),
  WordModel(
    text: 'pena',
    newLetter: 'n ',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['pe', 'na'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'tucano',
    newLetter: 'n ',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['tu', 'ca', 'no'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'rato',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ra', 'to'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'rena',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['re', 'na'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'raia',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['rai', 'a'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'boi',
    newLetter: 'b',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['boi'],
    syllableCount: 1,
  ),
  WordModel(
    text: 'lobo',
    newLetter: 'b',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['lo', 'bo'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'baleia',
    newLetter: 'b',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ba', 'lei', 'a'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'gato',
    newLetter: 'g',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ga', 'to'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'galo',
    newLetter: 'g',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ga', 'lo'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'papagaio',
    newLetter: 'g',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['pa', 'pa', 'gai', 'o'],
    syllableCount: 4,
  ),
  WordModel(
    text: 'iguana',
    newLetter: 'g',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['i', 'gua', 'na'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'tartaruga',
    newLetter: 'g',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['tar', 'ta', 'ru', 'ga'],
    syllableCount: 4,
  ),
  WordModel(
    text: 'juba',
    newLetter: 'j',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ju', 'ba'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'javali',
    newLetter: 'j',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ja', 'va', 'li'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'foca',
    newLetter: 'f',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['fo', 'ca'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'sapo',
    newLetter: 's',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['sa', 'po'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'hiena',
    newLetter: 'h',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['hi', 'e', 'na'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'hipopótamo',
    newLetter: 'h',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['hi', 'po', 'pó', 'ta', 'mo'],
    syllableCount: 5,
    audioFileName: 'hipopotamo',
    imageFileName: 'hipopotamo',
  ),
  WordModel(
    text: 'peixe',
    newLetter: 'x',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['pei', 'xe'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'mocho',
    newLetter: 'ch',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['mo', 'cho'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'ninho',
    newLetter: 'nh',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ni', 'nho'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'minhoca',
    newLetter: 'nh',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['mi', 'nho', 'ca'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'galinha',
    newLetter: 'nh',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ga', 'li', 'nha'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'andorinha',
    newLetter: 'nh',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['an', 'do', 'ri', 'nha'],
    syllableCount: 4,
  ),
  WordModel(
    text: 'gafanhoto',
    newLetter: 'nh',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ga', 'fa', 'nho', 'to'],
    syllableCount: 4,
  ),
  WordModel(
    text: 'joaninha',
    newLetter: 'nh',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['jo', 'a', 'ni', 'nha'],
    syllableCount: 4,
  ),
  WordModel(
    text: 'cabra',
    newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ca', 'bra'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'zebra',
    newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ze', 'bra'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'cobra',
    newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['co', 'bra'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'crocodilo',
    newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['cro', 'co', 'di', 'lo'],
    syllableCount: 4,
  ),
  WordModel(
    text: 'dragão',
    newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['dra', 'gão'],
    syllableCount: 2,
    audioFileName: 'dragao',
    imageFileName: 'dragao',
  ),
  WordModel(
    text: 'tigre',
    newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
    topic: 'animais',
    difficulty: 'baixa',
    syllables: ['ti', 'gre'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'roxo',
    newLetter: 'x',
    topic: 'cores',
    difficulty: 'baixa',
    syllables: ['ro', 'xo'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'preto',
    newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
    topic: 'cores',
    difficulty: 'baixa',
    syllables: ['pre', 'to'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'oito',
    newLetter: 't',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['oi', 'to'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'um',
    newLetter: 'm',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['um'],
    syllableCount: 1,
  ),
  WordModel(
    text: 'nove',
    newLetter: 'n ',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['no', 've'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'sete',
    newLetter: 's',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['se', 'te'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'zero',
    newLetter: 'z',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['ze', 'ro'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'dez',
    newLetter: 'z',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['dez'],
    syllableCount: 1,
  ),
  WordModel(
    text: 'onze',
    newLetter: 'z',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['on', 'ze'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'doze',
    newLetter: 'z',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['do', 'ze'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'quinze',
    newLetter: 'z',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['quin', 'ze'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'dezoito',
    newLetter: 'z',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['de', 'zoi', 'to'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'dezanove',
    newLetter: 'z',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['de', 'za', 'no', 've'],
    syllableCount: 4,
  ),
  WordModel(
    text: 'três',
    newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['três'],
    syllableCount: 1,
    audioFileName: 'tres',
    imageFileName: 'tres',
  ),
  WordModel(
    text: 'quatro',
    newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['qua', 'tro'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'treze',
    newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
    topic: 'numeros',
    difficulty: 'baixa',
    syllables: ['tre', 'ze'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'polvo',
    newLetter: 'v',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['pol', 'vo'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'caracol',
    newLetter: 'c',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['ca', 'ra', 'col'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'panda',
    newLetter: 'n',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['pan', 'da'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'arara',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['a', 'ra', 'ra'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'peru',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['pe', 'ru'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'tubarão',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['tu', 'ba', 'rão'],
    syllableCount: 3,
    audioFileName: 'tubarao',
    imageFileName: 'tubarao',
  ),
  WordModel(
    text: 'porco',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['por', 'co'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'escorpião',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['es', 'cor', 'pi', 'ão'],
    syllableCount: 4,
    audioFileName: 'escorpiao',
    imageFileName: 'escorpiao',
  ),
  WordModel(
    text: 'unicórnio',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['u', 'ni', 'cór', 'ni', 'o'],
    syllableCount: 5,
    audioFileName: 'unicornio',
    imageFileName: 'unicornio',
  ),
  WordModel(
    text: 'burro',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['bu', 'rro'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'orca',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['or', 'ca'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'borboleta',
    newLetter: 'b',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['bor', 'bo', 'le', 'ta'],
    syllableCount: 4,
  ),
  WordModel(
    text: 'águia',
    newLetter: 'g',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['á', 'gui', 'a'],
    syllableCount: 3,
    audioFileName: 'aguia',
    imageFileName: 'aguia',
  ),
  WordModel(
    text: 'girafa',
    newLetter: 'g',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['gi', 'ra', 'fa'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'golfinho',
    newLetter: 'g',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['gol', 'fi', 'nho'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'pinguim',
    newLetter: 'g',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['pin', 'guim'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'canguru',
    newLetter: 'g',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['can', 'gu', 'ru'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'formiga',
    newLetter: 'f',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['for', 'mi', 'ga'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'elefante',
    newLetter: 'f',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['e', 'le', 'fan', 'te'],
    syllableCount: 4,
  ),
  WordModel(
    text: 'esquilo',
    newLetter: 's',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['es', 'qui', 'lo'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'urso',
    newLetter: 's',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['ur', 'so'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'cisne',
    newLetter: 's',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['cis', 'ne'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'dinossauro',
    newLetter: 's',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['di', 'no', 'ssau', 'ro'],
    syllableCount: 4,
  ),
  WordModel(
    text: 'cegonha',
    newLetter: 'nh',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['ce', 'go', 'nha'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'golfinho',
    newLetter: 'nh',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['gol', 'fi', 'nho'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'aranha',
    newLetter: 'nh',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['a', 'ra', 'nha'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'coelho',
    newLetter: 'lh',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['co', 'e', 'lho'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'bacalhau',
    newLetter: 'lh',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['ba', 'ca', 'lhau'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'ovelha',
    newLetter: 'lh',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['o', 've', 'lha'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'abelha',
    newLetter: 'lh',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['a', 'be', 'lha'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'avestruz',
    newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['a', 'ves', 'truz'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'flamingo',
    newLetter: 'bl, cl, fl, gl, pl, tl',
    topic: 'animais',
    difficulty: 'media',
    syllables: ['fla', 'min', 'go'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'pincel',
    newLetter: 'n ',
    topic: 'cores',
    difficulty: 'media',
    syllables: ['pin', 'cel'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'verde',
    newLetter: 'r',
    topic: 'cores',
    difficulty: 'media',
    syllables: ['ver', 'de'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'amarelo',
    newLetter: 'r',
    topic: 'cores',
    difficulty: 'media',
    syllables: ['a', 'ma', 're', 'lo'],
    syllableCount: 4,
  ),
  WordModel(
    text: 'azul',
    newLetter: 'z',
    topic: 'cores',
    difficulty: 'media',
    syllables: ['a', 'zul'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'cinzento',
    newLetter: 'z',
    topic: 'cores',
    difficulty: 'media',
    syllables: ['cin', 'zen', 'to'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'castanho',
    newLetter: 'nh',
    topic: 'cores',
    difficulty: 'media',
    syllables: ['cas', 'ta', 'nho'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'vermelho',
    newLetter: 'lh',
    topic: 'cores',
    difficulty: 'media',
    syllables: ['ver', 'me', 'lho'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'branco',
    newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
    topic: 'cores',
    difficulty: 'media',
    syllables: ['bran', 'co'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'cinco',
    newLetter: 'c',
    topic: 'numeros',
    difficulty: 'media',
    syllables: ['cin', 'co'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'vinte',
    newLetter: 'n ',
    topic: 'numeros',
    difficulty: 'media',
    syllables: ['vin', 'te'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'dois',
    newLetter: 's',
    topic: 'numeros',
    difficulty: 'media',
    syllables: ['dois'],
    syllableCount: 1,
  ),
  WordModel(
    text: 'seis',
    newLetter: 's',
    topic: 'numeros',
    difficulty: 'media',
    syllables: ['seis'],
    syllableCount: 1,
  ),
  WordModel(
    text: 'catorze',
    newLetter: 'n ',
    topic: 'numeros',
    difficulty: 'media',
    syllables: ['ca', 'tor', 'ze'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'dezasseis',
    newLetter: 's',
    topic: 'numeros',
    difficulty: 'media',
    syllables: ['de', 'za', 'sseis'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'dezassete',
    newLetter: 's',
    topic: 'numeros',
    difficulty: 'media',
    syllables: ['de', 'za', 'sse', 'te'],
    syllableCount: 4,
  ),
  WordModel(
    text: 'caça',
    newLetter: 'c',
    topic: 'animais',
    difficulty: 'dificil',
    syllables: ['ca', 'ça'],
    syllableCount: 2,
    audioFileName: 'caca',
    imageFileName: 'caca',
  ),
  WordModel(
    text: 'ouriço',
    newLetter: 'c',
    topic: 'animais',
    difficulty: 'dificil',
    syllables: ['ou', 'ri', 'ço'],
    syllableCount: 3,
    audioFileName: 'ourico',
    imageFileName: 'ourico',
  ),
  WordModel(
    text: 'melro',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'dificil',
    syllables: ['mel', 'ro'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'potro',
    newLetter: 'r',
    topic: 'animais',
    difficulty: 'dificil',
    syllables: ['pol', 'tro'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'pombo',
    newLetter: 'b',
    topic: 'animais',
    difficulty: 'dificil',
    syllables: ['pom', 'bo'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'raposa',
    newLetter: 's',
    topic: 'animais',
    difficulty: 'dificil',
    syllables: ['ra', 'po', 'sa'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'mosca',
    newLetter: 's',
    topic: 'animais',
    difficulty: 'dificil',
    syllables: ['mos', 'ca'],
    syllableCount: 2,
  ),
  WordModel(
    text: 'mosquito',
    newLetter: 's',
    topic: 'animais',
    difficulty: 'dificil',
    syllables: ['mos', 'qui', 'to'],
    syllableCount: 3,
  ),
  WordModel(
    text: 'chimpanzé',
    newLetter: 'ch',
    topic: 'animais',
    difficulty: 'dificil',
    syllables: ['chim', 'pan', 'zé'],
    syllableCount: 3,
    audioFileName: 'chimpanze',
    imageFileName: 'chimpanze',
  ),
  WordModel(
    text: 'escaravelho',
    newLetter: 'lh',
    topic: 'animais',
    difficulty: 'dificil',
    syllables: ['es', 'ca', 'ra', 've', 'lho'],
    syllableCount: 5,
  ),
  WordModel(
    text: 'desenho',
    newLetter: 'nh',
    topic: 'cores',
    difficulty: 'dificil',
    syllables: ['de', 'se', 'nho'],
    syllableCount: 3,
  ),
];
