import 'package:hive/hive.dart';
part 'word_model.g.dart';

@HiveType(typeId: 2)
class WordModel extends HiveObject {
  @HiveField(0)
  String text;

  @HiveField(1)
  String newLetter;

  @HiveField(2)
  String topic;

  @HiveField(3)
  String difficulty; // "baixa", "media", "elevada"

  @HiveField(4)
  List<String> syllables;

  @HiveField(5)
  int syllableCount;

  @HiveField(6)
  String? audioFileName; // exceção manual para casos de nomes com acentuação, caractéres especiais ou espaços 

  @HiveField(7)
  String? imageFileName; // exceção manual para casos de nomes com acentuação, caractéres especiais ou espaços 

  WordModel({
    required this.text,
    required this.newLetter,
    required this.topic,
    required this.difficulty,
    required this.syllables,
    required this.syllableCount,
    this.audioFileName,
    this.imageFileName,
  });

  String get audioPath => 'assets/sounds/words_characters${audioFileName ?? text}.ogg';
  String get imagePath => 'assets/images/words${imageFileName ?? text}.webp';
}


Future<void> populateWordsIfNeeded(List<WordModel> words) async {
  final box = await Hive.openBox<WordModel>('words');

  if (box.isEmpty) {
    for (final word in words) {
      await box.add(word);
    }
  }
}


final List<WordModel> words = [
WordModel(
  text: 'pia',
  newLetter: 'p',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['pia'],
  syllableCount: 1,
),
WordModel(
  text: 'piu',
  newLetter: 'p',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['piu'],
  syllableCount: 1,
),
WordModel(
  text: 'pato',
  newLetter: 't',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['pa', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'tatu',
  newLetter: 't',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ta', 'tu'],
  syllableCount: 2,
),
WordModel(
  text: 'lã',
  newLetter: 'l',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['lã'],
  syllableCount: 1,
  audioFileName: 'la',
  imageFileName: 'la',
),
WordModel(
  text: 'leão',
  newLetter: 'l',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['le','ão'],
  syllableCount: 2,
  audioFileName: 'leao',
  imageFileName: 'leao',
),
WordModel(
  text: 'lula',
  newLetter: 'l',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['lu', 'la'],
  syllableCount: 2,
),
WordModel(
  text: 'lapa',
  newLetter: 'l',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['la', 'pa'],
  syllableCount: 2,
),
WordModel(
  text: 'mia',
  newLetter: 'm',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['mia'],
  syllableCount: 1,
),
WordModel(
  text: 'puma',
  newLetter: 'm',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['pu', 'ma'],
  syllableCount: 2,
),
WordModel(
  text: 'lama',
  newLetter: 'm',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['la', 'ma'],
  syllableCount: 2,
),
WordModel(
  text: 'vaca',
  newLetter: 'v',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['va', 'ca'],
  syllableCount: 2,
),
WordModel(
  text: 'pavão',
  newLetter: 'v',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['pa', 'vão'],
  syllableCount: 2,
  audioFileName: 'pavao',
  imageFileName: 'pavao',
),
WordModel(
  text: 'veado',
  newLetter: 'v',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ve', 'a', 'do'],
  syllableCount: 3,
),
WordModel(
  text: 'cão',
  newLetter: 'c',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['cão'],
  syllableCount: 1,
  audioFileName: 'cao',
  imageFileName: 'cao',
),
WordModel(
  text: 'toca',
  newLetter: 'c',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['to', 'ca'],
  syllableCount: 2,
),
WordModel(
  text: 'cuco',
  newLetter: 'c',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['cu', 'co'],
  syllableCount: 2,
),
WordModel(
  text: 'macaco',
  newLetter: 'c',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ma', 'ca', 'co'],
  syllableCount: 3,
),
WordModel(
  text: 'cavalo',
  newLetter: 'c',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ca', 'va', 'lo'],
  syllableCount: 3,
),
WordModel(
  text: 'camelo',
  newLetter: 'c',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ca', 'me', 'lo'],
  syllableCount: 3,
),
WordModel(
  text: 'camaleão',
  newLetter: 'c',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ca', 'ma', 'le', 'ão'],
  syllableCount: 4,
  audioFileName: 'camaleao',
  imageFileName: 'camaleao',
),
WordModel(
  text: 'pena',
  newLetter: 'n ',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['pe', 'na'],
  syllableCount: 2,
),
WordModel(
  text: 'tucano',
  newLetter: 'n ',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['tu', 'ca', 'no'],
  syllableCount: 3,
),
WordModel(
  text: 'rato',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ra', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'rena',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['re', 'na'],
  syllableCount: 2,
),
WordModel(
  text: 'raia',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['rai','a'],
  syllableCount: 2,
),
WordModel(
  text: 'boi',
  newLetter: 'b',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['boi'],
  syllableCount: 1,
),
WordModel(
  text: 'lobo',
  newLetter: 'b',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['lo', 'bo'],
  syllableCount: 2,
),
WordModel(
  text: 'baleia',
  newLetter: 'b',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ba', 'lei', 'a'],
  syllableCount: 3,
),
WordModel(
  text: 'gato',
  newLetter: 'g',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ga', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'galo',
  newLetter: 'g',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ga', 'lo'],
  syllableCount: 2,
),
WordModel(
  text: 'canguru',
  newLetter: 'g',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['can', 'gu', 'ru'],
  syllableCount: 3,
),
WordModel(
  text: 'papagaio',
  newLetter: 'g',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['pa', 'pa', 'gai', 'o'],
  syllableCount: 4,
),
WordModel(
  text: 'iguana',
  newLetter: 'g',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['i', 'gua', 'na'],
  syllableCount: 3,
),
WordModel(
  text: 'tartaruga',
  newLetter: 'g',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['tar', 'ta', 'ru', 'ga'],
  syllableCount: 4,
),
WordModel(
  text: 'juba',
  newLetter: 'j',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ju', 'ba'],
  syllableCount: 2,
),
WordModel(
  text: 'javali',
  newLetter: 'j',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ja', 'va', 'li'],
  syllableCount: 3,
),
WordModel(
  text: 'foca',
  newLetter: 'f',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['fo', 'ca'],
  syllableCount: 2,
),
WordModel(
  text: 'sapo',
  newLetter: 's',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['sa', 'po'],
  syllableCount: 2,
),
WordModel(
  text: 'hiena',
  newLetter: 'h',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['hi', 'e', 'na'],
  syllableCount: 3,
),
WordModel(
  text: 'hipopótamo',
  newLetter: 'h',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['hi', 'po', 'pó', 'ta', 'mo'],
  syllableCount: 5,
  audioFileName: 'hipopotamo',
  imageFileName: 'hipopotamo',
),
WordModel(
  text: 'peixe',
  newLetter: 'x',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['pei', 'xe'],
  syllableCount: 2,
),
WordModel(
  text: 'texugo',
  newLetter: 'x',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['te', 'xu', 'go'],
  syllableCount: 3,
),
WordModel(
  text: 'mocho',
  newLetter: 'ch',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['mo', 'cho'],
  syllableCount: 2,
),
WordModel(
  text: 'ninho',
  newLetter: 'nh',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ni', 'nho'],
  syllableCount: 2,
),
WordModel(
  text: 'minhoca',
  newLetter: 'nh',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['mi', 'nho', 'ca'],
  syllableCount: 3,
),
WordModel(
  text: 'galinha',
  newLetter: 'nh',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ga', 'li', 'nha'],
  syllableCount: 3,
),
WordModel(
  text: 'andorinha',
  newLetter: 'nh',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['an', 'do', 'ri', 'nha'],
  syllableCount: 4,
),
WordModel(
  text: 'gafanhoto',
  newLetter: 'nh',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ga', 'fa', 'nho', 'to'],
  syllableCount: 4,
),
WordModel(
  text: 'joaninha',
  newLetter: 'nh',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['jo', 'a', 'ni', 'nha'],
  syllableCount: 4,
),
WordModel(
  text: 'cabra',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ca', 'bra'],
  syllableCount: 2,
),
WordModel(
  text: 'zebra',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ze', 'bra'],
  syllableCount: 2,
),
WordModel(
  text: 'cobra',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['co', 'bra'],
  syllableCount: 2,
),
WordModel(
  text: 'crocodilo',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['cro', 'co', 'di', 'lo'],
  syllableCount: 4,
),
WordModel(
  text: 'dragão',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['dra', 'gão'],
  syllableCount: 2,
  audioFileName: 'dragao',
  imageFileName: 'dragao',
),
WordModel(
  text: 'tigre',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'animais',
  difficulty: 'baixa',
  syllables: ['ti', 'gre'],
  syllableCount: 2,
),
WordModel(
  text: 'cinzento',
  newLetter: 'z',
  topic: 'cores',
  difficulty: 'baixa',
  syllables: ['cin', 'zen', 'to'],
  syllableCount: 3,
),
WordModel(
  text: 'roxo',
  newLetter: 'x',
  topic: 'cores',
  difficulty: 'baixa',
  syllables: ['ro', 'xo'],
  syllableCount: 2,
),
WordModel(
  text: 'preto',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'cores',
  difficulty: 'baixa',
  syllables: ['pre', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'pé',
  newLetter: 'p',
  topic: 'corpo',
  difficulty: 'baixa',
  syllables: ['pé'],
  syllableCount: 1,
  audioFileName: 'pe',
  imageFileName: 'pe',
),
WordModel(
  text: 'pelo',
  newLetter: 'l',
  topic: 'corpo',
  difficulty: 'baixa',
  syllables: ['pe', 'lo'],
  syllableCount: 2,
),
WordModel(
  text: 'dedo',
  newLetter: 'd',
  topic: 'corpo',
  difficulty: 'baixa',
  syllables: ['de', 'do'],
  syllableCount: 2,
),
WordModel(
  text: 'mão',
  newLetter: 'm',
  topic: 'corpo',
  difficulty: 'baixa',
  syllables: ['mão'],
  syllableCount: 1,
  audioFileName: 'mao',
  imageFileName: 'mao',
),
WordModel(
  text: 'boca',
  newLetter: 'b',
  topic: 'corpo',
  difficulty: 'baixa',
  syllables: ['bo', 'ca'],
  syllableCount: 2,
),
WordModel(
  text: 'cabelo',
  newLetter: 'b',
  topic: 'corpo',
  difficulty: 'baixa',
  syllables: ['ca', 'be', 'lo'],
  syllableCount: 3,
),
WordModel(
  text: 'bigode',
  newLetter: 'g',
  topic: 'corpo',
  difficulty: 'baixa',
  syllables: ['bi', 'go', 'de'],
  syllableCount: 3,
),
WordModel(
  text: 'unha',
  newLetter: 'nh',
  topic: 'corpo',
  difficulty: 'baixa',
  syllables: ['u', 'nha'],
  syllableCount: 2,
),
WordModel(
  text: 'olho',
  newLetter: 'lh',
  topic: 'corpo',
  difficulty: 'baixa',
  syllables: ['o', 'lho'],
  syllableCount: 2,
),
WordModel(
  text: 'tapete',
  newLetter: 't',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['ta', 'pe', 'te'],
  syllableCount: 3,
),
WordModel(
  text: 'mala',
  newLetter: 'm',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['ma', 'la'],
  syllableCount: 2,
),
WordModel(
  text: 'mola',
  newLetter: 'm',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['mo', 'la'],
  syllableCount: 2,
),
WordModel(
  text: 'cadeira',
  newLetter: 'c',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['ca', 'dei', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'cama',
  newLetter: 'c',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['ca', 'ma'],
  syllableCount: 2,
),
WordModel(
  text: 'copo',
  newLetter: 'c',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['co', 'po'],
  syllableCount: 2,
),
WordModel(
  text: 'panela',
  newLetter: 'n ',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['pa', 'ne', 'la'],
  syllableCount: 3,
),
WordModel(
  text: 'bule',
  newLetter: 'b',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['bu', 'le'],
  syllableCount: 2,
),
WordModel(
  text: 'cabide',
  newLetter: 'b',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['ca', 'bi', 'de'],
  syllableCount: 3,
),
WordModel(
  text: 'gaveta',
  newLetter: 'g',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['ga', 've', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'tijolo',
  newLetter: 'j',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['ti', 'jo', 'lo'],
  syllableCount: 3,
),
WordModel(
  text: 'janela',
  newLetter: 'j',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['ja', 'ne', 'la'],
  syllableCount: 3,
),
WordModel(
  text: 'faca',
  newLetter: 'f',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['fa', 'ca'],
  syllableCount: 2,
),
WordModel(
  text: 'fogão',
  newLetter: 'f',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['fo', 'gão'],
  syllableCount: 2,
  audioFileName: 'fogao',
  imageFileName: 'fogao',
),
WordModel(
  text: 'sofá',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['so', 'fá'],
  syllableCount: 2,
),
WordModel(
  text: 'sala',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['sa', 'la'],
  syllableCount: 2,
),
WordModel(
  text: 'sabonete',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['sa', 'bo', 'ne', 'te'],
  syllableCount: 4,
),
WordModel(
  text: 'sanita',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['sa', 'ni', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'chave',
  newLetter: 'ch',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['cha', 've'],
  syllableCount: 2,
),
WordModel(
  text: 'fechadura',
  newLetter: 'ch',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['fe', 'cha', 'du', 'ra'],
  syllableCount: 4,
),
WordModel(
  text: 'chaminé',
  newLetter: 'ch',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['cha', 'mi', 'né'],
  syllableCount: 3,
  audioFileName: 'chamine',
  imageFileName: 'chamine',
),
WordModel(
  text: 'chávena',
  newLetter: 'ch',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['chá', 've', 'na'],
  syllableCount: 3,
  audioFileName: 'chavena',
  imageFileName: 'chavena',
),
WordModel(
  text: 'beliche',
  newLetter: 'ch',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['be', 'li', 'che'],
  syllableCount: 3,
),
WordModel(
  text: 'banheira',
  newLetter: 'nh',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['ba', 'nhei', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'toalha',
  newLetter: 'nh',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['to', 'a', 'lha'],
  syllableCount: 3,
),
WordModel(
  text: 'vidro',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['vi', 'dro'],
  syllableCount: 2,
),
WordModel(
  text: 'fruteira',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['fru', 'tei', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'frigorifico',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['fri', 'go', 'ri', 'fi', 'co'],
  syllableCount: 5,
),
WordModel(
  text: 'livro',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'casa',
  difficulty: 'baixa',
  syllables: ['li', 'vro'],
  syllableCount: 2,
),
WordModel(
  text: 'meia',
  newLetter: 'm',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['mei', 'a'],
  syllableCount: 2,
),
WordModel(
  text: 'cueca',
  newLetter: 'c',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['cu', 'e', 'ca'],
  syllableCount: 3,
),
WordModel(
  text: 'colete',
  newLetter: 'c',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['co', 'le', 'te'],
  syllableCount: 3,
),
WordModel(
  text: 'capacete',
  newLetter: 'c',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['ca', 'pa', 'ce', 'te'],
  syllableCount: 4,
),
WordModel(
  text: 'roupa',
  newLetter: 'r',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['rou', 'pa'],
  syllableCount: 2,
),
WordModel(
  text: 'botão',
  newLetter: 'b',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['bo', 'tão'],
  syllableCount: 2,
  audioFileName: 'botao',
  imageFileName: 'botao',
),
WordModel(
  text: 'boné',
  newLetter: 'b',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['bo', 'né'],
  syllableCount: 2,
  audioFileName: 'bone',
  imageFileName: 'bone',
),
WordModel(
  text: 'bota',
  newLetter: 'b',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['bo', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'bata',
  newLetter: 'b',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['ba', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'babete',
  newLetter: 'b',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['ba', 'be', 'te'],
  syllableCount: 3,
),
WordModel(
  text: 'biquini',
  newLetter: 'b',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['bi', 'qui', 'ni'],
  syllableCount: 3,
),
WordModel(
  text: 'fato',
  newLetter: 'f',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['fa', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'fita',
  newLetter: 'f',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['fi', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'fivela',
  newLetter: 'f',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['fi', 've', 'la'],
  syllableCount: 3,
),
WordModel(
  text: 'saia',
  newLetter: 's',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['sai', 'a'],
  syllableCount: 2,
),
WordModel(
  text: 'sandália',
  newLetter: 's',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['san', 'dá', 'li', 'a'],
  syllableCount: 4,
  audioFileName: 'sandalia',
  imageFileName: 'sandalia',
),
WordModel(
  text: 'chinelo',
  newLetter: 'ch',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['chi', 'ne', 'lo'],
  syllableCount: 3,
),
WordModel(
  text: 'chapéu',
  newLetter: 'ch',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['cha', 'péu'],
  syllableCount: 2,
  audioFileName: 'chapeu',
  imageFileName: 'chapeu',
),
WordModel(
  text: 'fato de banho',
  newLetter: 'nh',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['fa', 'to ', 'de ', 'ba', 'nho'],
  syllableCount: 5,
  audioFileName: 'fato_de_banho',
  imageFileName: 'fato_de_banho',
),
WordModel(
  text: 'gravata',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'roupa',
  difficulty: 'baixa',
  syllables: ['gra', 'va', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'oito',
  newLetter: 't',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['oi', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'um',
  newLetter: 'm',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['um'],
  syllableCount: 1,
),
WordModel(
  text: 'nove',
  newLetter: 'n ',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['no', 've'],
  syllableCount: 2,
),
WordModel(
  text: 'sete',
  newLetter: 's',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['se', 'te'],
  syllableCount: 2,
),
WordModel(
  text: 'zero',
  newLetter: 'z',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['ze', 'ro'],
  syllableCount: 2,
),
WordModel(
  text: 'dez',
  newLetter: 'z',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['dez'],
  syllableCount: 1,
),
WordModel(
  text: 'onze',
  newLetter: 'z',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['on', 'ze'],
  syllableCount: 2,
),
WordModel(
  text: 'doze',
  newLetter: 'z',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['do', 'ze'],
  syllableCount: 2,
),
WordModel(
  text: 'quinze',
  newLetter: 'z',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['quin', 'ze'],
  syllableCount: 2,
),
WordModel(
  text: 'dezasseis',
  newLetter: 'z',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['de', 'zas', 'seis'],
  syllableCount: 3,
),
WordModel(
  text: 'dezassete',
  newLetter: 'z',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['de', 'zas', 'se', 'te'],
  syllableCount: 4,
),
WordModel(
  text: 'dezoito',
  newLetter: 'z',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['de', 'zoi', 'to'],
  syllableCount: 3,
),
WordModel(
  text: 'dezanove',
  newLetter: 'z',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['de', 'za', 'no', 've'],
  syllableCount: 4,
),
WordModel(
  text: 'três',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['três'],
  syllableCount: 1,
  audioFileName: 'tres',
  imageFileName: 'tres',
),
WordModel(
  text: 'quatro',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['qua', 'tro'],
  syllableCount: 2,
),
WordModel(
  text: 'treze',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'numeros',
  difficulty: 'baixa',
  syllables: ['tre', 'ze'],
  syllableCount: 2,
),
WordModel(
  text: 'pão',
  newLetter: 'p',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['pão'],
  syllableCount: 1,
  audioFileName: 'pao',
  imageFileName: 'pao',
),
WordModel(
  text: 'papa',
  newLetter: 'p',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['pa', 'pa'],
  syllableCount: 2,
),
WordModel(
  text: 'pepita',
  newLetter: 'p',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['pe', 'pi', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'papaia',
  newLetter: 'p',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['pa', 'pai', 'a'],
  syllableCount: 3,
),
WordModel(
  text: 'tomate',
  newLetter: 't',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['to', 'ma', 'te'],
  syllableCount: 3,
),
WordModel(
  text: 'leite',
  newLetter: 'l',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['lei', 'te'],
  syllableCount: 2,
),
WordModel(
  text: 'lata',
  newLetter: 'l',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['la', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'melão',
  newLetter: 'm',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['me', 'lão'],
  syllableCount: 2,
  audioFileName: 'melao',
  imageFileName: 'melao',
),
WordModel(
  text: 'limão',
  newLetter: 'm',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['li', 'mão'],
  syllableCount: 2,
  audioFileName: 'limao',
  imageFileName: 'limao',
),
WordModel(
  text: 'meloa',
  newLetter: 'm',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['me', 'loa'],
  syllableCount: 2,
),
WordModel(
  text: 'ovo',
  newLetter: 'v',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['ovo'],
  syllableCount: 1,
),
WordModel(
  text: 'cocô',
  newLetter: 'c',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['co','cô'],
  syllableCount: 2,
  audioFileName: 'coco',
  imageFileName: 'coco',
),
WordModel(
  text: 'couve',
  newLetter: 'c',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['cou', 've'],
  syllableCount: 2,
),
WordModel(
  text: 'doce',
  newLetter: 'c',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['do', 'ce'],
  syllableCount: 2,
),
WordModel(
  text: 'pacote',
  newLetter: 'c',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['pa', 'co', 'te'],
  syllableCount: 3,
),
WordModel(
  text: 'quivi',
  newLetter: 'q',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['qui', 'vi'],
  syllableCount: 2,
),
WordModel(
  text: 'queque',
  newLetter: 'q',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['que', 'que'],
  syllableCount: 2,
),
WordModel(
  text: 'banana',
  newLetter: 'b',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['ba', 'na', 'na'],
  syllableCount: 3,
),
WordModel(
  text: 'pepino',
  newLetter: 'n ',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['pe', 'pi', 'no'],
  syllableCount: 3,
),
WordModel(
  text: 'canela',
  newLetter: 'n ',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['ca', 'ne', 'la'],
  syllableCount: 3,
),
WordModel(
  text: 'romã',
  newLetter: 'r',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['ro', 'mã'],
  syllableCount: 2,
  audioFileName: 'roma',
  imageFileName: 'roma',
),
WordModel(
  text: 'bolo',
  newLetter: 'b',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['bo', 'lo'],
  syllableCount: 2,
),
WordModel(
  text: 'nabo',
  newLetter: 'b',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['na', 'bo'],
  syllableCount: 2,
),
WordModel(
  text: 'batata',
  newLetter: 'b',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['ba', 'ta', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'bolota',
  newLetter: 'b',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['bo', 'lo', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'abóbora',
  newLetter: 'b',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['a', 'bó', 'bo', 'ra'],
  syllableCount: 4,
  audioFileName: 'abobora',
  imageFileName: 'abobora',
),
WordModel(
  text: 'cebola',
  newLetter: 'b',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['ce', 'bo', 'la'],
  syllableCount: 3,
),
WordModel(
  text: 'água',
  newLetter: 'g',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['á', 'gua'],
  syllableCount: 2,
  audioFileName: 'agua',
  imageFileName: 'agua',
),
WordModel(
  text: 'cogumelo',
  newLetter: 'g',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['co', 'gu', 'me', 'lo'],
  syllableCount: 4,
),
WordModel(
  text: 'cereja',
  newLetter: 'j',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['ce', 're', 'ja'],
  syllableCount: 3,
),
WordModel(
  text: 'queijo',
  newLetter: 'j',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['quei', 'jo'],
  syllableCount: 2,
),
WordModel(
  text: 'fava',
  newLetter: 'f',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['fa', 'va'],
  syllableCount: 2,
),
WordModel(
  text: 'bife',
  newLetter: 'f',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['bi', 'fe'],
  syllableCount: 2,
),
WordModel(
  text: 'feijão',
  newLetter: 'f',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['fei', 'jão'],
  syllableCount: 2,
  audioFileName: 'feijao',
  imageFileName: 'feijao',
),
WordModel(
  text: 'sopa',
  newLetter: 's',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['so', 'pa'],
  syllableCount: 2,
),
WordModel(
  text: 'sumo',
  newLetter: 's',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['su', 'mo'],
  syllableCount: 2,
),
WordModel(
  text: 'salada',
  newLetter: 's',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['sa', 'la', 'da'],
  syllableCount: 3,
),
WordModel(
  text: 'azeite',
  newLetter: 'z',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['a', 'zei', 'te'],
  syllableCount: 3,
),
WordModel(
  text: 'xarope',
  newLetter: 'x',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['xa', 'ro', 'pe'],
  syllableCount: 3,
),
WordModel(
  text: 'ameixa',
  newLetter: 'x',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['a', 'mei', 'xa'],
  syllableCount: 3,
),
WordModel(
  text: 'chá',
  newLetter: 'ch',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['chá'],
  syllableCount: 1,
  audioFileName: 'cha',
  imageFileName: 'cha',
),
WordModel(
  text: 'bolacha',
  newLetter: 'ch',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['bo', 'la', 'cha'],
  syllableCount: 3,
),
WordModel(
  text: 'chocolate',
  newLetter: 'ch',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['cho', 'co', 'la', 'te'],
  syllableCount: 4,
),
WordModel(
  text: 'milho',
  newLetter: 'lh',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['mi', 'lho'],
  syllableCount: 2,
),
WordModel(
  text: 'fiambre',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['fi', 'am', 'bre'],
  syllableCount: 3,
),
WordModel(
  text: 'bróculos',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['bró', 'cu', 'los'],
  syllableCount: 3,
  audioFileName: 'broculos',
  imageFileName: 'broculos',
),
WordModel(
  text: 'fruta',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'comida',
  difficulty: 'baixa',
  syllables: ['fru', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'pai',
  newLetter: 'p',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['pai'],
  syllableCount: 1,
),
WordModel(
  text: 'mãe',
  newLetter: 'm',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['mãe'],
  syllableCount: 1,
  audioFileName: 'mae',
  imageFileName: 'mae', 
),
WordModel(
  text: 'avó',
  newLetter: 'v',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['a', 'vó'],
  syllableCount: 2,
  audioFileName: 'avo_f',
  imageFileName: 'avo_f',
),
WordModel(
  text: 'avô',
  newLetter: 'v',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['a', 'vô'],
  syllableCount: 2,
  audioFileName: 'avo_m',
  imageFileName: 'avo_m',
),
WordModel(
  text: 'detetive',
  newLetter: 'v',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['de', 'te', 'ti', 've'],
  syllableCount: 4,
),
WordModel(
  text: 'médico',
  newLetter: 'c',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['mé', 'di', 'co'],
  syllableCount: 3,
  audioFileName: 'medico',
  imageFileName: 'medico',
),
WordModel(
  text: 'polícia',
  newLetter: 'c',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['po', 'li', 'ci','a'],
  syllableCount: 4,
  audioFileName: 'policia',
  imageFileName: 'policia',
),
WordModel(
  text: 'noiva',
  newLetter: 'n ',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['noi', 'va'],
  syllableCount: 2,
),
WordModel(
  text: 'rei',
  newLetter: 'r',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['rei'],
  syllableCount: 1,
),
WordModel(
  text: 'bebé',
  newLetter: 'b',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['be', 'bé'],
  syllableCount: 2,
  audioFileName: 'bebe',
  imageFileName: 'bebe',
),
WordModel(
  text: 'fada',
  newLetter: 'f',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['fa', 'da'],
  syllableCount: 2,
),
WordModel(
  text: 'herói',
  newLetter: 'h',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['he', 'rói'],
  syllableCount: 2,
  audioFileName: 'heroi',
  imageFileName: 'heroi',
),
WordModel(
  text: 'rainha',
  newLetter: 'nh',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['ra', 'i', 'nha'],
  syllableCount: 3,
),
WordModel(
  text: 'filho',
  newLetter: 'lh',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['fi', 'lho'],
  syllableCount: 2,
),
WordModel(
  text: 'filha',
  newLetter: 'lh',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['fi', 'lha'],
  syllableCount: 2,
),
WordModel(
  text: 'bruxa',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['bru', 'xa'],
  syllableCount: 2,
),
WordModel(
  text: 'princesa',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['prin', 'ce', 'sa'],
  syllableCount: 3,
),
WordModel(
  text: 'atleta',
  newLetter: 'bl, cl, fl, gl, pl, tl',
  topic: 'pessoas',
  difficulty: 'baixa',
  syllables: ['a', 'tle', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'pau',
  newLetter: 'p',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['pau'],
  syllableCount: 1,
),
WordModel(
  text: 'tulipa',
  newLetter: 'l',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['tu', 'li', 'pa'],
  syllableCount: 3,
),
WordModel(
  text: 'pétala',
  newLetter: 'l',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['pé', 'ta', 'la'],
  syllableCount: 3,
  audioFileName: 'petala',
  imageFileName: 'petala',
),
WordModel(
  text: 'lua',
  newLetter: 'l',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['lua'],
  syllableCount: 1,
),
WordModel(
  text: 'mata',
  newLetter: 'm',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['ma', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'cato',
  newLetter: 'c',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['ca', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'nuvem',
  newLetter: 'n ',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['nu', 'vem'],
  syllableCount: 2,
),
WordModel(
  text: 'neve',
  newLetter: 'n ',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['ne', 've'],
  syllableCount: 2,
),
WordModel(
  text: 'vento',
  newLetter: 'n ',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['ven', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'onda',
  newLetter: 'n ',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['on', 'da'],
  syllableCount: 2,
),
WordModel(
  text: 'noite',
  newLetter: 'n ',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['noi', 'te'],
  syllableCount: 2,
),
WordModel(
  text: 'rio',
  newLetter: 'r',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['rio'],
  syllableCount: 1,
),
WordModel(
  text: 'hera',
  newLetter: 'h',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['he', 'ra'],
  syllableCount: 2,
),
WordModel(
  text: 'chuva',
  newLetter: 'ch',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['chu', 'va'],
  syllableCount: 2,
),
WordModel(
  text: 'pinheiro',
  newLetter: 'nh',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['pi', 'nhei', 'ro'],
  syllableCount: 3,
),
WordModel(
  text: 'cozinheira',
  newLetter: 'nh',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['co', 'zi', 'nhei', 'ra'],
  syllableCount: 4,
),
WordModel(
  text: 'folha',
  newLetter: 'lh',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['fo', 'lha'],
  syllableCount: 2,
),
WordModel(
  text: 'cravo',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['cra', 'vo'],
  syllableCount: 2,
),
WordModel(
  text: 'pedra',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['pe', 'dra'],
  syllableCount: 2,
),
WordModel(
  text: 'gruta',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['gru', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'trevo',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['tre', 'vo'],
  syllableCount: 2,
),
WordModel(
  text: 'planeta',
  newLetter: 'bl, cl, fl, gl, pl, tl',
  topic: 'natureza',
  difficulty: 'baixa',
  syllables: ['pla', 'ne', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'viola',
  newLetter: 'v',
  topic: 'musica',
  difficulty: 'baixa',
  syllables: ['vi', 'o', 'la'],
  syllableCount: 3,
),
WordModel(
  text: 'piano',
  newLetter: 'n ',
  topic: 'musica',
  difficulty: 'baixa',
  syllables: ['pi', 'a', 'no'],
  syllableCount: 3,
),
WordModel(
  text: 'violino',
  newLetter: 'n ',
  topic: 'musica',
  difficulty: 'baixa',
  syllables: ['vi', 'o', 'li', 'no'],
  syllableCount: 4,
),
WordModel(
  text: 'rádio',
  newLetter: 'r',
  topic: 'musica',
  difficulty: 'baixa',
  syllables: ['rá', 'di', 'o'],
  syllableCount: 3,
  audioFileName: 'radio',
  imageFileName: 'radio',
),
WordModel(
  text: 'bateria',
  newLetter: 'b',
  topic: 'musica',
  difficulty: 'baixa',
  syllables: ['ba', 'te', 'ria'],
  syllableCount: 3,
),
WordModel(
  text: 'xilofone',
  newLetter: 'x',
  topic: 'musica',
  difficulty: 'baixa',
  syllables: ['xi', 'lo', 'fo', 'ne'],
  syllableCount: 4,
),
WordModel(
  text: 'microfone',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'musica',
  difficulty: 'baixa',
  syllables: ['mi', 'cro', 'fo', 'ne'],
  syllableCount: 4,
),
WordModel(
  text: 'flauta',
  newLetter: 'bl, cl, fl, gl, pl, tl',
  topic: 'musica',
  difficulty: 'baixa',
  syllables: ['flau', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'pá',
  newLetter: 'p',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['pá'],
  syllableCount: 1,
  audioFileName: 'pa',
  imageFileName: 'pa',
),
WordModel(
  text: 'pipa',
  newLetter: 'p',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['pi', 'pa'],
  syllableCount: 2,
),
WordModel(
  text: 'pião',
  newLetter: 'p',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['pi', 'ão'],
  syllableCount: 2,
  audioFileName: 'piao',
  imageFileName: 'piao',
),
WordModel(
  text: 'ata',
  newLetter: 't',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ata'],
  syllableCount: 1,
),
WordModel(
  text: 'totó',
  newLetter: 't',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['to', 'tó'],
  syllableCount: 2,
  audioFileName: 'toto',
  imageFileName: 'toto',
),
WordModel(
  text: 'pote',
  newLetter: 't',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['po', 'te'],
  syllableCount: 2,
),
WordModel(
  text: 'lupa',
  newLetter: 'l',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['lu', 'pa'],
  syllableCount: 2,
),
WordModel(
  text: 'pala',
  newLetter: 'l',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['pa', 'la'],
  syllableCount: 2,
),
WordModel(
  text: 'apito',
  newLetter: 'l',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['a', 'pi', 'to'],
  syllableCount: 3,
),
WordModel(
  text: 'dedada',
  newLetter: 'l',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['de', 'da', 'da'],
  syllableCount: 3,
),
WordModel(
  text: 'dado',
  newLetter: 'd',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['da', 'do'],
  syllableCount: 2,
),
WordModel(
  text: 'dia',
  newLetter: 'd',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['dia'],
  syllableCount: 1,
),
WordModel(
  text: 'data',
  newLetter: 'd',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['da', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'mapa',
  newLetter: 'm',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ma', 'pa'],
  syllableCount: 2,
),
WordModel(
  text: 'mota',
  newLetter: 'm',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['mo', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'dama',
  newLetter: 'm',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['da', 'ma'],
  syllableCount: 2,
),
WordModel(
  text: 'meta',
  newLetter: 'm',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['me', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'muleta',
  newLetter: 'm',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['mu', 'le', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'camião',
  newLetter: 'm',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ca', 'mi', 'ão'],
  syllableCount: 3,
  audioFileName: 'camiao',
  imageFileName: 'camiao',
),
WordModel(
  text: 'vela',
  newLetter: 'v',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ve', 'la'],
  syllableCount: 2,
),
WordModel(
  text: 'avião',
  newLetter: 'v',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['a', 'vi', 'ão'],
  syllableCount: 3,
  audioFileName: 'aviao',
  imageFileName: 'aviao',
),
WordModel(
  text: 'capa',
  newLetter: 'c',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ca', 'pa'],
  syllableCount: 2,
),
WordModel(
  text: 'cola',
  newLetter: 'c',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['co', 'la'],
  syllableCount: 2,
),
WordModel(
  text: 'cone',
  newLetter: 'c',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['co', 'ne'],
  syllableCount: 2,
),
WordModel(
  text: 'leque',
  newLetter: 'q',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['le', 'que'],
  syllableCount: 2,
),
WordModel(
  text: 'queda',
  newLetter: 'q',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['que', 'da'],
  syllableCount: 2,
),
WordModel(
  text: 'piquenique',
  newLetter: 'q',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['pi', 'que', 'ni', 'que'],
  syllableCount: 4,
),
WordModel(
  text: 'nave',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['na', 've'],
  syllableCount: 2,
),
WordModel(
  text: 'pino',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['pi', 'no'],
  syllableCount: 2,
),
WordModel(
  text: 'caneta',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ca', 'ne', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'novelo',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['no', 've', 'lo'],
  syllableCount: 3,
),
WordModel(
  text: 'canoa',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ca', 'no', 'a'],
  syllableCount: 3,
),
WordModel(
  text: 'dominó',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['do', 'mi', 'nó'],
  syllableCount: 3,
  audioFileName: 'domino',
  imageFileName: 'domino',
),
WordModel(
  text: 'remo',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['re', 'mo'],
  syllableCount: 2,
),
WordModel(
  text: 'rede',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['re', 'de'],
  syllableCount: 2,
),
WordModel(
  text: 'roda',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ro', 'da'],
  syllableCount: 2,
),
WordModel(
  text: 'rua',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['rua'],
  syllableCount: 1,
),
WordModel(
  text: 'raqueta',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ra', 'que', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'balão',
  newLetter: 'b',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ba', 'lão'],
  syllableCount: 2,
  audioFileName: 'balao',
  imageFileName: 'balao',
),
WordModel(
  text: 'bola',
  newLetter: 'b',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['bo', 'la'],
  syllableCount: 2,
),
WordModel(
  text: 'boneca',
  newLetter: 'b',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['bo', 'ne', 'ca'],
  syllableCount: 3,
),
WordModel(
  text: 'gota',
  newLetter: 'g',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['go', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'régua',
  newLetter: 'g',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ré', 'gua'],
  syllableCount: 2,
  audioFileName: 'regua',
  imageFileName: 'regua',
),
WordModel(
  text: 'jogo',
  newLetter: 'j',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['jo', 'go'],
  syllableCount: 2,
),
WordModel(
  text: 'jipe',
  newLetter: 'j',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ji', 'pe'],
  syllableCount: 2,
),
WordModel(
  text: 'jato',
  newLetter: 'j',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ja', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'loja',
  newLetter: 'j',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['lo', 'ja'],
  syllableCount: 2,
),
WordModel(
  text: 'fumo',
  newLetter: 'f',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['fu', 'mo'],
  syllableCount: 2,
),
WordModel(
  text: 'fogo',
  newLetter: 'f',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['fo', 'go'],
  syllableCount: 2,
),
WordModel(
  text: 'afia',
  newLetter: 'f',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['a', 'fi', 'a'],
  syllableCount: 3,
),
WordModel(
  text: 'ferida',
  newLetter: 'f',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['fe', 'ri', 'da'],
  syllableCount: 3,
),
WordModel(
  text: 'sino',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['si', 'no'],
  syllableCount: 2,
),
WordModel(
  text: 'saco',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['sa', 'co'],
  syllableCount: 2,
),
WordModel(
  text: 'sirene',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['si', 're', 'ne'],
  syllableCount: 3,
),
WordModel(
  text: 'semáforo',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['se', 'má', 'fo', 'ro'],
  syllableCount: 4,
  audioFileName: 'semaforo',
  imageFileName: 'semaforo',
),
WordModel(
  text: 'feliz',
  newLetter: 'z',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['fe', 'liz'],
  syllableCount: 2,
),
WordModel(
  text: 'giz',
  newLetter: 'z',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['giz'],
  syllableCount: 1,
),
WordModel(
  text: 'baliza',
  newLetter: 'z',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ba', 'li', 'za'],
  syllableCount: 3,
),
WordModel(
  text: 'buzina',
  newLetter: 'z',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['bu', 'zi', 'na'],
  syllableCount: 3,
),
WordModel(
  text: 'hora',
  newLetter: 'h',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['ho', 'ra'],
  syllableCount: 2,
),
WordModel(
  text: 'caixa',
  newLetter: 'x',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['cai', 'xa'],
  syllableCount: 2,
),
WordModel(
  text: 'lixo',
  newLetter: 'x',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['li', 'xo'],
  syllableCount: 2,
),
WordModel(
  text: 'repuxo',
  newLetter: 'x',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['re', 'pu', 'xo'],
  syllableCount: 3,
),
WordModel(
  text: 'chupeta',
  newLetter: 'ch',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['chu', 'pe', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'mochila',
  newLetter: 'ch',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['mo', 'chi', 'la'],
  syllableCount: 3,
),
WordModel(
  text: 'peluche',
  newLetter: 'ch',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['pe', 'lu', 'che'],
  syllableCount: 3,
),
WordModel(
  text: 'cheiro',
  newLetter: 'ch',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['chei', 'ro'],
  syllableCount: 2,
),
WordModel(
  text: 'dinheiro',
  newLetter: 'nh',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['di', 'nhei', 'ro'],
  syllableCount: 3,
),
WordModel(
  text: 'moinho',
  newLetter: 'nh',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['moi', 'nho'],
  syllableCount: 2,
),
WordModel(
  text: 'palha',
  newLetter: 'lh',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['pa', 'lha'],
  syllableCount: 2,
),
WordModel(
  text: 'ilha',
  newLetter: 'lh',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['i', 'lha'],
  syllableCount: 2,
),
WordModel(
  text: 'quadro',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['qua', 'dro'],
  syllableCount: 2,
),
WordModel(
  text: 'xadrez',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['xa', 'drez'],
  syllableCount: 2,
),
WordModel(
  text: 'frio',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['fri', 'o'],
  syllableCount: 2,
),
WordModel(
  text: 'igreja',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['i', 'gre', 'ja'],
  syllableCount: 3,
),
WordModel(
  text: 'prego',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['pre', 'go'],
  syllableCount: 2,
),
WordModel(
  text: 'primeiro',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['pri', 'mei', 'ro'],
  syllableCount: 3,
),
WordModel(
  text: 'bicicleta',
  newLetter: 'bl, cl, fl, gl, pl, tl',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['bi', 'ci', 'cle', 'ta'],
  syllableCount: 4,
),
WordModel(
  text: 'globo',
  newLetter: 'bl, cl, fl, gl, pl, tl',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['glo', 'bo'],
  syllableCount: 2,
),
WordModel(
  text: 'iglu',
  newLetter: 'bl, cl, fl, gl, pl, tl',
  topic: 'outros',
  difficulty: 'baixa',
  syllables: ['i', 'glu'],
  syllableCount: 2,
),
WordModel(
  text: 'polvo',
  newLetter: 'v',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['pol', 'vo'],
  syllableCount: 2,
),
WordModel(
  text: 'caracol',
  newLetter: 'c',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['ca', 'ra', 'col'],
  syllableCount: 3,
),
WordModel(
  text: 'panda',
  newLetter: 'n',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['pan', 'da'],
  syllableCount: 2,
),
WordModel(
  text: 'tinta',
  newLetter: 'n ',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['tin', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'arara',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['a', 'ra', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'peru',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['pe', 'ru'],
  syllableCount: 2,
),
WordModel(
  text: 'tubarão',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['tu', 'ba', 'rão'],
  syllableCount: 3,
  audioFileName: 'tubarao',
  imageFileName: 'tubarao',
),
WordModel(
  text: 'porco',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['por', 'co'],
  syllableCount: 2,
),
WordModel(
  text: 'escorpião',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['es', 'cor', 'pi', 'ão'],
  syllableCount: 4,
  audioFileName: 'escorpiao',
  imageFileName: 'escorpiao',
),
WordModel(
  text: 'unicórnio',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['u', 'ni', 'cór', 'ni', 'o'],
  syllableCount: 5,
  audioFileName: 'unicornio',
  imageFileName: 'unicornio',
),
WordModel(
  text: 'burro',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['bur', 'ro'],
  syllableCount: 2,
),
WordModel(
  text: 'orca',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['or', 'ca'],
  syllableCount: 2,
),
WordModel(
  text: 'borboleta',
  newLetter: 'b',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['bor', 'bo', 'le', 'ta'],
  syllableCount: 4,
),
WordModel(
  text: 'águia',
  newLetter: 'g',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['á', 'gui', 'a'],
  syllableCount: 3,
  audioFileName: 'aguia',
  imageFileName: 'aguia',
),
WordModel(
  text: 'girafa',
  newLetter: 'g',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['gi', 'ra', 'fa'],
  syllableCount: 3,
),
WordModel(
  text: 'golfinho',
  newLetter: 'g',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['gol', 'fi', 'nho'],
  syllableCount: 3,
),
WordModel(
  text: 'pinguim',
  newLetter: 'g',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['pin', 'guim'],
  syllableCount: 2,
),
WordModel(
  text: 'formiga',
  newLetter: 'f',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['for', 'mi', 'ga'],
  syllableCount: 3,
),
WordModel(
  text: 'elefante',
  newLetter: 'f',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['ele', 'fan', 'te'],
  syllableCount: 3,
),
WordModel(
  text: 'esquilo',
  newLetter: 's',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['es', 'qui', 'lo'],
  syllableCount: 3,
),
WordModel(
  text: 'urso',
  newLetter: 's',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['ur', 'so'],
  syllableCount: 2,
),
WordModel(
  text: 'cisne',
  newLetter: 's',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['cis', 'ne'],
  syllableCount: 2,
),
WordModel(
  text: 'cães',
  newLetter: 's',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['cães'],
  syllableCount: 1,
  audioFileName: 'caes',
  imageFileName: 'caes',
),
WordModel(
  text: 'cegonha',
  newLetter: 'nh',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['ce', 'go', 'nha'],
  syllableCount: 3,
),
WordModel(
  text: 'golfinho',
  newLetter: 'nh',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['gol', 'fi', 'nho'],
  syllableCount: 3,
),
WordModel(
  text: 'aranha',
  newLetter: 'nh',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['a', 'ra', 'nha'],
  syllableCount: 3,
),
WordModel(
  text: 'coelho',
  newLetter: 'lh',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['co', 'e', 'lho'],
  syllableCount: 3,
),
WordModel(
  text: 'bacalhau',
  newLetter: 'lh',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['ba', 'ca', 'lhau'],
  syllableCount: 3,
),
WordModel(
  text: 'ovelha',
  newLetter: 'lh',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['o', 've', 'lha'],
  syllableCount: 3,
),
WordModel(
  text: 'abelha',
  newLetter: 'lh',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['a', 'be', 'lha'],
  syllableCount: 3,
),
WordModel(
  text: 'avestruz',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['a', 'ves', 'truz'],
  syllableCount: 3,
),
WordModel(
  text: 'flamingo',
  newLetter: 'bl, cl, fl, gl, pl, tl',
  topic: 'animais',
  difficulty: 'media',
  syllables: ['fla', 'min', 'go'],
  syllableCount: 3,
),
WordModel(
  text: 'pincel',
  newLetter: 'n ',
  topic: 'cores',
  difficulty: 'media',
  syllables: ['pin', 'cel'],
  syllableCount: 2,
),
WordModel(
  text: 'verde',
  newLetter: 'r',
  topic: 'cores',
  difficulty: 'media',
  syllables: ['ver', 'de'],
  syllableCount: 2,
),
WordModel(
  text: 'amarelo',
  newLetter: 'r',
  topic: 'cores',
  difficulty: 'media',
  syllables: ['a', 'ma', 're', 'lo'],
  syllableCount: 4,
),
WordModel(
  text: 'azul',
  newLetter: 'z',
  topic: 'cores',
  difficulty: 'media',
  syllables: ['a', 'zul'],
  syllableCount: 2,
),
WordModel(
  text: 'castanho',
  newLetter: 'nh',
  topic: 'cores',
  difficulty: 'media',
  syllables: ['cas', 'ta', 'nho'],
  syllableCount: 3,
),
WordModel(
  text: 'vermelho',
  newLetter: 'lh',
  topic: 'cores',
  difficulty: 'media',
  syllables: ['ver', 'me', 'lho'],
  syllableCount: 3,
),
WordModel(
  text: 'branco',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'cores',
  difficulty: 'media',
  syllables: ['bran', 'co'],
  syllableCount: 2,
),
WordModel(
  text: 'palma',
  newLetter: 'm',
  topic: 'corpo',
  difficulty: 'media',
  syllables: ['pal', 'ma'],
  syllableCount: 2,
),
WordModel(
  text: 'dente',
  newLetter: 'n ',
  topic: 'corpo',
  difficulty: 'media',
  syllables: ['den', 'te'],
  syllableCount: 2,
),
WordModel(
  text: 'perna',
  newLetter: 'r',
  topic: 'corpo',
  difficulty: 'media',
  syllables: ['per', 'na'],
  syllableCount: 2,
),
WordModel(
  text: 'barba',
  newLetter: 'b',
  topic: 'corpo',
  difficulty: 'media',
  syllables: ['bar', 'ba'],
  syllableCount: 2,
),
WordModel(
  text: 'língua',
  newLetter: 'g',
  topic: 'corpo',
  difficulty: 'media',
  syllables: ['lín', 'gua'],
  syllableCount: 2,
  audioFileName: 'lingua',
  imageFileName: 'lingua',
),
WordModel(
  text: 'costas',
  newLetter: 's',
  topic: 'corpo',
  difficulty: 'media',
  syllables: ['cos', 'tas'],
  syllableCount: 2,
),
WordModel(
  text: 'testa',
  newLetter: 's',
  topic: 'corpo',
  difficulty: 'media',
  syllables: ['tes', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'nariz',
  newLetter: 'z',
  topic: 'corpo',
  difficulty: 'media',
  syllables: ['na', 'riz'],
  syllableCount: 2,
),
WordModel(
  text: 'orelha',
  newLetter: 'lh',
  topic: 'corpo',
  difficulty: 'media',
  syllables: ['ore', 'lha'],
  syllableCount: 2,
),
WordModel(
  text: 'joelho',
  newLetter: 'lh',
  topic: 'corpo',
  difficulty: 'media',
  syllables: ['jo', 'e', 'lho'],
  syllableCount: 3,
),
WordModel(
  text: 'sobrancelha',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'corpo',
  difficulty: 'media',
  syllables: ['so', 'bran', 'ce', 'lha'],
  syllableCount: 4,
),
WordModel(
  text: 'quarto',
  newLetter: 'q',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['quar', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'avental',
  newLetter: 'n ',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['a', 'ven', 'tal'],
  syllableCount: 3,
),
WordModel(
  text: 'pente',
  newLetter: 'n ',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['pen', 'te'],
  syllableCount: 2,
),
WordModel(
  text: 'banco',
  newLetter: 'n ',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['ban', 'co'],
  syllableCount: 2,
),
WordModel(
  text: 'portão',
  newLetter: 'r',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['por', 'tão'],
  syllableCount: 2,
  audioFileName: 'portao',
  imageFileName: 'portao',
),
WordModel(
  text: 'porta',
  newLetter: 'r',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['por', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'carta',
  newLetter: 'r',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['car', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'elevador',
  newLetter: 'r',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['e', 'le', 'va', 'dor'],
  syllableCount: 4,
),
WordModel(
  text: 'almofada',
  newLetter: 'r',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['al', 'mo', 'fa', 'da'],
  syllableCount: 4,
),
WordModel(
  text: 'torradeira',
  newLetter: 'r',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['tor', 'ra', 'dei', 'ra'],
  syllableCount: 4,
),
WordModel(
  text: 'lareira',
  newLetter: 'r',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['la', 'rei', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'relógio',
  newLetter: 'g',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['re', 'ló', 'gio'],
  syllableCount: 3,
  audioFileName: 'relogio',
  imageFileName: 'relogio',
),
WordModel(
  text: 'tigela',
  newLetter: 'g',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['ti', 'ge', 'la'],
  syllableCount: 3,
),
WordModel(
  text: 'garfo',
  newLetter: 'g',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['gar', 'fo'],
  syllableCount: 2,
),
WordModel(
  text: 'funil',
  newLetter: 'f',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['fu', 'nil'],
  syllableCount: 2,
),
WordModel(
  text: 'secador',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['se', 'ca', 'dor'],
  syllableCount: 3,
),
WordModel(
  text: 'pasta de dentes',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['pas', 'ta  ', 'de ', 'den', 'tes'],
  syllableCount: 5,
  audioFileName: 'pasta_de_dentes',
  imageFileName: 'pasta_de_dentes',
),
WordModel(
  text: 'escova',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['es', 'co', 'va'],
  syllableCount: 3,
),
WordModel(
  text: 'escada',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['es', 'ca', 'da'],
  syllableCount: 3,
),
WordModel(
  text: 'vassoura',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['vas', 'sou', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'cesto',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['ces', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'cozinha',
  newLetter: 'z',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['co', 'zi', 'nha'],
  syllableCount: 3,
),
WordModel(
  text: 'horta',
  newLetter: 'h',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['hor', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'telhado',
  newLetter: 'lh',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['te', 'lha', 'do'],
  syllableCount: 3,
),
WordModel(
  text: 'espelho',
  newLetter: 'lh',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['es', 'pe', 'lho'],
  syllableCount: 3,
),
WordModel(
  text: 'colher',
  newLetter: 'lh',
  topic: 'casa',
  difficulty: 'media',
  syllables: ['co', 'lher'],
  syllableCount: 2,
),
WordModel(
  text: 'cinto',
  newLetter: 'c',
  topic: 'roupa',
  difficulty: 'media',
  syllables: ['cin', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'anel',
  newLetter: 'n ',
  topic: 'roupa',
  difficulty: 'media',
  syllables: ['a', 'nel'],
  syllableCount: 2,
),
WordModel(
  text: 'gorro',
  newLetter: 'r',
  topic: 'roupa',
  difficulty: 'media',
  syllables: ['gor', 'ro'],
  syllableCount: 2,
),
WordModel(
  text: 'pulseira',
  newLetter: 's',
  topic: 'roupa',
  difficulty: 'media',
  syllables: ['pul', 'sei', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'luvas',
  newLetter: 's',
  topic: 'roupa',
  difficulty: 'media',
  syllables: ['lu', 'vas'],
  syllableCount: 2,
),
WordModel(
  text: 'óculos',
  newLetter: 's',
  topic: 'roupa',
  difficulty: 'media',
  syllables: ['ó', 'cu', 'los'],
  syllableCount: 3,
  audioFileName: 'oculos',
  imageFileName: 'oculos',
),
WordModel(
  text: 'sapatos',
  newLetter: 's',
  topic: 'roupa',
  difficulty: 'media',
  syllables: ['sa', 'pa', 'tos'],
  syllableCount: 3,
),
WordModel(
  text: 'capuz',
  newLetter: 'z',
  topic: 'roupa',
  difficulty: 'media',
  syllables: ['ca', 'puz'],
  syllableCount: 2,
),
WordModel(
  text: 'quatorze',
  newLetter: 'z',
  topic: 'numeros',
  difficulty: 'media',
  syllables: ['qua', 'tor', 'ze'],
  syllableCount: 3,
),
WordModel(
  text: 'galochas',
  newLetter: 'ch',
  topic: 'roupa',
  difficulty: 'media',
  syllables: ['ga', 'lo', 'chas'],
  syllableCount: 3,
),
WordModel(
  text: 'cachecol',
  newLetter: 'ch',
  topic: 'roupa',
  difficulty: 'media',
  syllables: ['ca', 'che', 'col'],
  syllableCount: 3,
),
WordModel(
  text: 'cinco',
  newLetter: 'c',
  topic: 'numeros',
  difficulty: 'media',
  syllables: ['cin', 'co'],
  syllableCount: 2,
),
WordModel(
  text: 'natal',
  newLetter: 'n ',
  topic: 'numeros',
  difficulty: 'media',
  syllables: ['na', 'tal'],
  syllableCount: 2,
),
WordModel(
  text: 'vinte',
  newLetter: 'n ',
  topic: 'numeros',
  difficulty: 'media',
  syllables: ['vin', 'te'],
  syllableCount: 2,
),
WordModel(
  text: 'dois',
  newLetter: 's',
  topic: 'numeros',
  difficulty: 'media',
  syllables: ['dois'],
  syllableCount: 1,
),
WordModel(
  text: 'seis',
  newLetter: 's',
  topic: 'numeros',
  difficulty: 'media',
  syllables: ['seis'],
  syllableCount: 1,
),
WordModel(
  text: 'mel',
  newLetter: 'm',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['mel'],
  syllableCount: 1,
),
WordModel(
  text: 'pudim',
  newLetter: 'm',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['pu', 'dim'],
  syllableCount: 2,
),
WordModel(
  text: 'atum',
  newLetter: 'm',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['a', 'tum'],
  syllableCount: 2,
),
WordModel(
  text: 'cenoura',
  newLetter: 'r',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['ce', 'nou', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'panqueca',
  newLetter: 'n ',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['pan', 'que', 'ca'],
  syllableCount: 3,
),
WordModel(
  text: 'torrada',
  newLetter: 'r',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['tor', 'ra', 'da'],
  syllableCount: 3,
),
WordModel(
  text: 'pera',
  newLetter: 'r',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['pe', 'ra'],
  syllableCount: 2,
),
WordModel(
  text: 'amora',
  newLetter: 'r',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['a', 'mo', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'comer',
  newLetter: 'r',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['co', 'mer'],
  syllableCount: 2,
),
WordModel(
  text: 'gelado',
  newLetter: 'g',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['ge', 'la', 'do'],
  syllableCount: 3,
),
WordModel(
  text: 'gelo',
  newLetter: 'g',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['ge', 'lo'],
  syllableCount: 2,
),
WordModel(
  text: 'gema',
  newLetter: 'g',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['ge', 'ma'],
  syllableCount: 2,
),
WordModel(
  text: 'gelatina',
  newLetter: 'g',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['ge', 'la', 'ti', 'na'],
  syllableCount: 4,
),
WordModel(
  text: 'manteiga',
  newLetter: 'g',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['man', 'tei', 'ga'],
  syllableCount: 3,
),
WordModel(
  text: 'morango',
  newLetter: 'g',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['mo', 'ran', 'go'],
  syllableCount: 3,
),
WordModel(
  text: 'manga',
  newLetter: 'g',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['man', 'ga'],
  syllableCount: 2,
),
WordModel(
  text: 'iogurte',
  newLetter: 'g',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['i', 'o', 'gur', 'te'],
  syllableCount: 4,
),
WordModel(
  text: 'laranja',
  newLetter: 'j',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['la', 'ran', 'ja'],
  syllableCount: 3,
),
WordModel(
  text: 'alface',
  newLetter: 'f',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['al', 'fa', 'ce'],
  syllableCount: 3,
),
WordModel(
  text: 'folar',
  newLetter: 'f',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['fo', 'lar'],
  syllableCount: 2,
),
WordModel(
  text: 'cereais',
  newLetter: 's',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['ce', 're', 'ais'],
  syllableCount: 3,
),
WordModel(
  text: 'feijões',
  newLetter: 's',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['fei', 'jões'],
  syllableCount: 2,
  audioFileName: 'feijoes',
  imageFileName: 'feijoes',
),
WordModel(
  text: 'uvas',
  newLetter: 's',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['u', 'vas'],
  syllableCount: 2,
),
WordModel(
  text: 'sandes',
  newLetter: 's',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['san', 'des'],
  syllableCount: 2,
),
WordModel(
  text: 'amendoins',
  newLetter: 's',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['a', 'men', 'do', 'ins'],
  syllableCount: 4,
),
WordModel(
  text: 'ananás',
  newLetter: 's',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['a', 'na', 'nás'],
  syllableCount: 3,
  audioFileName: 'ananas',
  imageFileName: 'ananas',
),
WordModel(
  text: 'pêssego',
  newLetter: 's',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['pês', 'se', 'go'],
  syllableCount: 3,
  audioFileName: 'pessego',
  imageFileName: 'pessego',
),
WordModel(
  text: 'massa',
  newLetter: 's',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['mas', 'sa'],
  syllableCount: 2,
),
WordModel(
  text: 'noz',
  newLetter: 'z',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['noz'],
  syllableCount: 1,
),
WordModel(
  text: 'azeitonas',
  newLetter: 'z',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['a', 'zei', 'to', 'nas'],
  syllableCount: 4,
),
WordModel(
  text: 'salsichas',
  newLetter: 'ch',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['sal', 'si', 'chas'],
  syllableCount: 3,
),
WordModel(
  text: 'lancheira',
  newLetter: 'ch',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['lan', 'chei', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'ervillhas',
  newLetter: 'lh',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['er', 'vil', 'lhas'],
  syllableCount: 3,
),
WordModel(
  text: 'frango',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'comida',
  difficulty: 'media',
  syllables: ['fran', 'go'],
  syllableCount: 2,
),
WordModel(
  text: 'pirata',
  newLetter: 'r',
  topic: 'pessoas',
  difficulty: 'media',
  syllables: ['pi', 'ra', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'pescador',
  newLetter: 's',
  topic: 'pessoas',
  difficulty: 'media',
  syllables: ['pes', 'ca', 'dor'],
  syllableCount: 3,
),
WordModel(
  text: 'dentista',
  newLetter: 's',
  topic: 'pessoas',
  difficulty: 'media',
  syllables: ['den', 'tis', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'rapaz',
  newLetter: 'z',
  topic: 'pessoas',
  difficulty: 'media',
  syllables: ['ra', 'paz'],
  syllableCount: 2,
),
WordModel(
  text: 'juiz',
  newLetter: 'z',
  topic: 'pessoas',
  difficulty: 'media',
  syllables: ['ju', 'iz'],
  syllableCount: 2,
),
WordModel(
  text: 'palhaço',
  newLetter: 'lh',
  topic: 'pessoas',
  difficulty: 'media',
  syllables: ['pa', 'lha', 'ço'],
  syllableCount: 3,
  audioFileName: 'palhaco',
  imageFileName: 'palhaco',
),
WordModel(
  text: 'professor',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'natureza',
  difficulty: 'media',
  syllables: ['pro', 'fes', 'sor'],
  syllableCount: 3,
),
WordModel(
  text: 'vento',
  newLetter: 'n ',
  topic: 'natureza',
  difficulty: 'media',
  syllables: ['ven', 'to'],
  syllableCount: 2,
),
WordModel(
  text: 'erva',
  newLetter: 'r',
  topic: 'natureza',
  difficulty: 'media',
  syllables: ['er', 'va'],
  syllableCount: 2,
),
WordModel(
  text: 'palmeira',
  newLetter: 'r',
  topic: 'natureza',
  difficulty: 'media',
  syllables: ['pal', 'mei', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'terra',
  newLetter: 'r',
  topic: 'natureza',
  difficulty: 'media',
  syllables: ['ter', 'ra'],
  syllableCount: 2,
),
WordModel(
  text: 'árvore',
  newLetter: 'r',
  topic: 'natureza',
  difficulty: 'media',
  syllables: ['ár', 'vo', 're'],
  syllableCount: 3,
  audioFileName: 'arvore',
  imageFileName: 'arvore',
),
WordModel(
  text: 'jardim',
  newLetter: 'j',
  topic: 'natureza',
  difficulty: 'media',
  syllables: ['jar', 'dim'],
  syllableCount: 2,
),
WordModel(
  text: 'sol',
  newLetter: 's',
  topic: 'natureza',
  difficulty: 'media',
  syllables: ['sol'],
  syllableCount: 1,
),
WordModel(
  text: 'floresta',
  newLetter: 'bl, cl, fl, gl, pl, tl',
  topic: 'natureza',
  difficulty: 'media',
  syllables: ['flo', 'res','ta'],
  syllableCount: 3,
),
WordModel(
  text: 'flor',
  newLetter: 'bl, cl, fl, gl, pl, tl',
  topic: 'natureza',
  difficulty: 'media',
  syllables: ['flor'],
  syllableCount: 1,
),
WordModel(
  text: 'palco',
  newLetter: 'c',
  topic: 'musica',
  difficulty: 'media',
  syllables: ['pal', 'co'],
  syllableCount: 2,
),
WordModel(
  text: 'canta',
  newLetter: 'c',
  topic: 'musica',
  difficulty: 'media',
  syllables: ['can', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'tambor',
  newLetter: 'r',
  topic: 'musica',
  difficulty: 'media',
  syllables: ['tam', 'bor'],
  syllableCount: 2,
),
WordModel(
  text: 'guitarra',
  newLetter: 'g',
  topic: 'musica',
  difficulty: 'media',
  syllables: ['gui', 'tar', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'harpa',
  newLetter: 'h',
  topic: 'musica',
  difficulty: 'media',
  syllables: ['har', 'pa'],
  syllableCount: 2,
),
WordModel(
  text: 'papel',
  newLetter: 'l',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['pa', 'pel'],
  syllableCount: 2,
),
WordModel(
  text: 'polpa',
  newLetter: 'l',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['pol', 'pa'],
  syllableCount: 2,
),
WordModel(
  text: 'dedal',
  newLetter: 'd',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['de', 'dal'],
  syllableCount: 2,
),
WordModel(
  text: 'voleibol',
  newLetter: 'v',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['vo', 'lei', 'bol'],
  syllableCount: 3,
),
WordModel(
  text: 'telemóvel',
  newLetter: 'v',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['te', 'le', 'mó', 'vel'],
  syllableCount: 4,
  audioFileName: 'telemovel',
  imageFileName: 'telemovel', 
),
WordModel(
  text: 'cinema',
  newLetter: 'c',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['ci', 'ne', 'ma'],
  syllableCount: 3,
),
WordModel(
  text: 'vacina',
  newLetter: 'c',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['va', 'ci', 'na'],
  syllableCount: 3,
),
WordModel(
  text: 'circulo',
  newLetter: 'c',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['cir', 'cu', 'lo'],
  syllableCount: 3,
),
WordModel(
  text: 'caderno',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['ca', 'der', 'no'],
  syllableCount: 3,
),
WordModel(
  text: 'ponte',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['pon', 'te'],
  syllableCount: 2,
),
WordModel(
  text: 'fonte',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['fon', 'te'],
  syllableCount: 2,
),
WordModel(
  text: 'diamante',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['di', 'a', 'man', 'te'],
  syllableCount: 4,
),
WordModel(
  text: 'tenda',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['ten', 'da'],
  syllableCount: 2,
),
WordModel(
  text: 'onda',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['on', 'da'],
  syllableCount: 2,
),
WordModel(
  text: 'nadar',
  newLetter: 'n ',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['na', 'dar'],
  syllableCount: 2,
),
WordModel(
  text: 'carnaval',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['car', 'na', 'val'],
  syllableCount: 3,
),
WordModel(
  text: 'terceiro',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['ter', 'cei', 'ro'],
  syllableCount: 3,
),
WordModel(
  text: 'dormir',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['dor', 'mir'],
  syllableCount: 2,
),
WordModel(
  text: 'lavar',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['la', 'var'],
  syllableCount: 2,
),
WordModel(
  text: 'parque',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['par', 'que'],
  syllableCount: 2,
),
WordModel(
  text: 'arco',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['ar', 'co'],
  syllableCount: 2,
),
WordModel(
  text: 'corda',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['cor', 'da'],
  syllableCount: 2,
),
WordModel(
  text: 'circo',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['cir', 'co'],
  syllableCount: 2,
),
WordModel(
  text: 'barco',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['bar', 'co'],
  syllableCount: 2,
),
WordModel(
  text: 'computador',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['com', 'pu', 'ta', 'dor'],
  syllableCount: 4,
),
WordModel(
  text: 'acro-íris',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['acro', 'í', 'ris'],
  syllableCount: 3,
  audioFileName: 'acro_iris', 
  imageFileName: 'acro_iris',
),
WordModel(
  text: 'pontapé',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['pon', 'ta', 'pé'],
  syllableCount: 3,
  audioFileName: 'pontape',
  imageFileName: 'pontape',
),
WordModel(
  text: 'carro',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['car', 'ro'],
  syllableCount: 2,
),
WordModel(
  text: 'torre',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['tor', 're'],
  syllableCount: 2,
),
WordModel(
  text: 'correr',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['cor', 'rer'],
  syllableCount: 2,
),
WordModel(
  text: 'autocarro',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['au', 'to', 'car', 'ro'],
  syllableCount: 4,
),
WordModel(
  text: 'correio',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['cor', 'rei', 'o'],
  syllableCount: 3,
),
WordModel(
  text: 'motor',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['mo', 'tor'],
  syllableCount: 2,
),
WordModel(
  text: 'cubo',
  newLetter: 'b',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['cu', 'bo'],
  syllableCount: 2,
),
WordModel(
  text: 'foguetão',
  newLetter: 'g',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['fo', 'gue', 'tão'],
  syllableCount: 3,
  audioFileName: 'foguetao',
  imageFileName: 'foguetao',
),
WordModel(
  text: 'gigante',
  newLetter: 'g',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['gi', 'gan', 'te'],
  syllableCount: 3,
),
WordModel(
  text: 'furador',
  newLetter: 'f',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['fu', 'ra', 'dor'],
  syllableCount: 3,
),
WordModel(
  text: 'fogueira',
  newLetter: 'f',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['fo', 'guei', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'futebol',
  newLetter: 'f',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['fu', 'te', 'bol'],
  syllableCount: 3,
),
WordModel(
  text: 'farol',
  newLetter: 'f',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['fa', 'rol'],
  syllableCount: 2,
),
WordModel(
  text: 'golfe',
  newLetter: 'f',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['gol', 'fe'],
  syllableCount: 2,
),
WordModel(
  text: 'segundo',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['se', 'gun', 'do'],
  syllableCount: 3,
),
WordModel(
  text: 'sinal',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['si', 'nal'],
  syllableCount: 2,
),
WordModel(
  text: 'basquetebol',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['bas', 'que', 'te', 'bol'],
  syllableCount: 4,
),
WordModel(
  text: 'festa',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['fes', 'ta'],
  syllableCount: 2,
),
WordModel(
  text: 'patins',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['pa', 'tins'],
  syllableCount: 2,
),
WordModel(
  text: 'ténis',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['té', 'nis'],
  syllableCount: 2,
),
WordModel(
  text: 'castelo',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['cas', 'te', 'lo'],
  syllableCount: 3,
),
WordModel(
  text: 'fósforo',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['fós', 'fo', 'ro'],
  syllableCount: 3,
  audioFileName: 'fosforo',
  imageFileName: 'fosforo',
),
WordModel(
  text: 'máscara',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['más', 'ca', 'ra'],
  syllableCount: 3,
  audioFileName: 'mascara',
  imageFileName: 'mascara',
),
WordModel(
  text: 'escola',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['es', 'co', 'la'],
  syllableCount: 3,
),
WordModel(
  text: 'osso',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['os', 'so'],
  syllableCount: 2,
),
WordModel(
  text: 'bússola',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['bús', 'so', 'la'],
  syllableCount: 3,
  audioFileName: 'bussola',
  imageFileName: 'bussola', 
),
WordModel(
  text: 'passadeira',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['pas', 'sa', 'dei', 'ra'],
  syllableCount: 4,
),
WordModel(
  text: 'girassol',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['gi', 'ras', 'sol'],
  syllableCount: 3,
),
WordModel(
  text: 'carrossel',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['car', 'ros', 'sel'],
  syllableCount: 3,
),
WordModel(
  text: 'lápis',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['lá', 'pis'],
  syllableCount: 2,
  audioFileName: 'lapis',
  imageFileName: 'lapis',
),
WordModel(
  text: 'búzio',
  newLetter: 'z',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['bú', 'zio'],
  syllableCount: 2,
  audioFileName: 'buzio',
  imageFileName: 'buzio',
),
WordModel(
  text: 'giz',
  newLetter: 'z',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['giz'],
  syllableCount: 1,
),
WordModel(
  text: 'azulejos',
  newLetter: 'z',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['azu', 'le', 'jos'],
  syllableCount: 3,
),
WordModel(
  text: 'anzol',
  newLetter: 'z',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['an', 'zol'],
  syllableCount: 2,
),
WordModel(
  text: 'hospital',
  newLetter: 'h',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['hos', 'pi', 'tal'],
  syllableCount: 3,
),
WordModel(
  text: 'hotel',
  newLetter: 'h',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['ho', 'tel'],
  syllableCount: 2,
),
WordModel(
  text: 'exame',
  newLetter: 'x',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['e', 'xa', 'me'],
  syllableCount: 3,
),
WordModel(
  text: 'borracha',
  newLetter: 'ch',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['bor', 'ra', 'cha'],
  syllableCount: 3,
),
WordModel(
  text: 'agulha',
  newLetter: 'nh',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['a', 'gu', 'lha'],
  syllableCount: 3,
),
WordModel(
  text: 'pinhal',
  newLetter: 'nh',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['pi', 'nhal'],
  syllableCount: 2,
),
WordModel(
  text: 'concha',
  newLetter: 'nh',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['con', 'cha'],
  syllableCount: 2,
),
WordModel(
  text: 'bilhete',
  newLetter: 'lh',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['bi', 'lhe', 'te'],
  syllableCount: 3,
),
WordModel(
  text: 'brincar',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['brin', 'car'],
  syllableCount: 2,
),
WordModel(
  text: 'cruz',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['cruz'],
  syllableCount: 1,
),
WordModel(
  text: 'frasco',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['fras', 'co'],
  syllableCount: 2,
),
WordModel(
  text: 'presente',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['pre', 'sen', 'te'],
  syllableCount: 3,
),
WordModel(
  text: 'trator',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['tra', 'tor'],
  syllableCount: 2,
),
WordModel(
  text: 'plasticina',
  newLetter: 'bl, cl, fl, gl, pl, tl',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['plas', 'ti', 'ci', 'na'],
  syllableCount: 4,
),
WordModel(
  text: 'gladiador',
  newLetter: 'bl, cl, fl, gl, pl, tl',
  topic: 'outros',
  difficulty: 'media',
  syllables: ['gla', 'di', 'a', 'dor'],
  syllableCount: 4,
),
WordModel(
  text: 'caça',
  newLetter: 'c',
  topic: 'animais',
  difficulty: 'dificil',
  syllables: ['ca', 'ça'],
  syllableCount: 2,
  audioFileName: 'caca',
  imageFileName: 'caca',
),
WordModel(
  text: 'ouriço',
  newLetter: 'c',
  topic: 'animais',
  difficulty: 'dificil',
  syllables: ['ou', 'ri', 'ço'],
  syllableCount: 3,
  audioFileName: 'ourico',
  imageFileName: 'ourico',
),
WordModel(
  text: 'melro',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'dificil',
  syllables: ['mel', 'ro'],
  syllableCount: 2,
),
WordModel(
  text: 'poltro',
  newLetter: 'r',
  topic: 'animais',
  difficulty: 'dificil',
  syllables: ['pol', 'tro'],
  syllableCount: 2,
),
WordModel(
  text: 'pombo',
  newLetter: 'b',
  topic: 'animais',
  difficulty: 'dificil',
  syllables: ['pom', 'bo'],
  syllableCount: 2,
),
WordModel(
  text: 'raposa',
  newLetter: 's',
  topic: 'animais',
  difficulty: 'dificil',
  syllables: ['ra', 'po', 'sa'],
  syllableCount: 3,
),
WordModel(
  text: 'mosca',
  newLetter: 's',
  topic: 'animais',
  difficulty: 'dificil',
  syllables: ['mos', 'ca'],
  syllableCount: 2,
),
WordModel(
  text: 'mosquito',
  newLetter: 's',
  topic: 'animais',
  difficulty: 'dificil',
  syllables: ['mos', 'qui', 'to'],
  syllableCount: 3,
),
WordModel(
  text: 'chimpanzé',
  newLetter: 'ch',
  topic: 'animais',
  difficulty: 'dificil',
  syllables: ['chim', 'pan', 'zé'],
  syllableCount: 3,
  audioFileName: 'chimpanze',
  imageFileName: 'chimpanze',
),
WordModel(
  text: 'escaravelho',
  newLetter: 'lh',
  topic: 'animais',
  difficulty: 'dificil',
  syllables: ['es', 'ca', 'ra', 've', 'lho'],
  syllableCount: 5,
),
WordModel(
  text: 'desenho',
  newLetter: 'nh',
  topic: 'cores',
  difficulty: 'dificil',
  syllables: ['de', 'se', 'nho'],
  syllableCount: 3,
),
WordModel(
  text: 'coração',
  newLetter: 'c',
  topic: 'corpo',
  difficulty: 'dificil',
  syllables: ['co', 'ra', 'ção'],
  syllableCount: 3,
  audioFileName: 'coracao',
  imageFileName: 'coracao',
),
WordModel(
  text: 'cabeça',
  newLetter: 'c',
  topic: 'corpo',
  difficulty: 'dificil',
  syllables: ['ca', 'be', 'ça'],
  syllableCount: 3,
  audioFileName: 'cabeca',
  imageFileName: 'cabeca',
),
WordModel(
  text: 'umbigo',
  newLetter: 'g',
  topic: 'corpo',
  difficulty: 'dificil',
  syllables: ['um', 'bi', 'go'],
  syllableCount: 3,
),
WordModel(
  text: 'ombros',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'corpo',
  difficulty: 'dificil',
  syllables: ['om', 'bros'],
  syllableCount: 2,
),
WordModel(
  text: 'sobrancelha',
  newLetter: 'lh',
  topic: 'corpo',
  difficulty: 'dificil',
  syllables: ['so', 'bran', 'ce', 'lha'],
  syllableCount: 4,
),
WordModel(
  text: 'braço',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'corpo',
  difficulty: 'dificil',
  syllables: ['bra', 'ço'],
  syllableCount: 2,
  audioFileName: 'braco',
  imageFileName: 'braco',
),
WordModel(
  text: 'balança',
  newLetter: 'b',
  topic: 'casa',
  difficulty: 'dificil',
  syllables: ['ba', 'lan', 'ça'],
  syllableCount: 3,
  audioFileName: 'balanca',
  imageFileName: 'balanca',
),
WordModel(
  text: 'mesa',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'dificil',
  syllables: ['me', 'sa'],
  syllableCount: 2,
),
WordModel(
  text: 'casa',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'dificil',
  syllables: ['ca', 'sa'],
  syllableCount: 2,
),
WordModel(
  text: 'casota',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'dificil',
  syllables: ['ca', 'so', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'vaso',
  newLetter: 's',
  topic: 'casa',
  difficulty: 'dificil',
  syllables: ['va', 'so'],
  syllableCount: 2,
),
WordModel(
  text: 'calças',
  newLetter: 'c',
  topic: 'roupa',
  difficulty: 'dificil',
  syllables: ['cal', 'ças'],
  syllableCount: 2,
  audioFileName: 'calcas',
  imageFileName: 'calcas',
),
WordModel(
  text: 'laço',
  newLetter: 'c',
  topic: 'roupa',
  difficulty: 'dificil',
  syllables: ['la', 'ço'],
  syllableCount: 2,
  audioFileName: 'laco',
  imageFileName: 'laco',
),
WordModel(
  text: 'camisa',
  newLetter: 's',
  topic: 'roupa',
  difficulty: 'dificil',
  syllables: ['ca', 'mi', 'sa'],
  syllableCount: 3,
),
WordModel(
  text: 'casaco',
  newLetter: 's',
  topic: 'roupa',
  difficulty: 'dificil',
  syllables: ['ca', 'sa', 'co'],
  syllableCount: 3,
),
WordModel(
  text: 'blusa',
  newLetter: 'bl, cl, fl, gl, pl, tl',
  topic: 'roupa',
  difficulty: 'dificil',
  syllables: ['blu', 'sa'],
  syllableCount: 2,
),
WordModel(
  text: 'compota',
  newLetter: 'm',
  topic: 'comida',
  difficulty: 'dificil',
  syllables: ['com', 'po', 'ta'],
  syllableCount: 3,
),
WordModel(
  text: 'açúcar',
  newLetter: 'c',
  topic: 'comida',
  difficulty: 'dificil',
  syllables: ['a', 'çú', 'car'],
  syllableCount: 3,
  audioFileName: 'acucar',
  imageFileName: 'acucar',
),
WordModel(
  text: 'rebuçado',
  newLetter: 'c',
  topic: 'comida',
  difficulty: 'dificil',
  syllables: ['re', 'bu', 'ça', 'do'],
  syllableCount: 4,
  audioFileName: 'rebucado',
  imageFileName: 'rebucado',
),
WordModel(
  text: 'maçã',
  newLetter: 'c',
  topic: 'comida',
  difficulty: 'dificil',
  syllables: ['ma', 'çã'],
  syllableCount: 2,
  audioFileName: 'maca',
  imageFileName: 'maca',
),
WordModel(
  text: 'bombom',
  newLetter: 'b',
  topic: 'comida',
  difficulty: 'dificil',
  syllables: ['bom', 'bom'],
  syllableCount: 2,
),
WordModel(
  text: 'arroz',
  newLetter: 'z',
  topic: 'comida',
  difficulty: 'dificil',
  syllables: ['ar', 'roz'],
  syllableCount: 2,
),
WordModel(
  text: 'piza',
  newLetter: 'z',
  topic: 'comida',
  difficulty: 'dificil',
  syllables: ['pi', 'za'],
  syllableCount: 2,
),
WordModel(
  text: 'bombeiro',
  newLetter: 'b',
  topic: 'pessoas',
  difficulty: 'dificil',
  syllables: ['bom', 'bei', 'ro'],
  syllableCount: 3,
),
WordModel(
  text: 'crianças',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'pessoas',
  difficulty: 'dificil',
  syllables: ['cri', 'an', 'ças'],
  syllableCount: 3,
  audioFileName: 'criancas',
  imageFileName: 'criancas',
),
WordModel(
  text: 'monstro',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'pessoas',
  difficulty: 'dificil',
  syllables: ['mons', 'tro'],
  syllableCount: 2,
),
WordModel(
  text: 'triste',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'pessoas',
  difficulty: 'dificil',
  syllables: ['tris', 'te'],
  syllableCount: 2,
),
WordModel(
  text: 'campo',
  newLetter: 'c',
  topic: 'natureza',
  difficulty: 'dificil',
  syllables: ['cam', 'po'],
  syllableCount: 2,
),
WordModel(
  text: 'rosa',
  newLetter: 's',
  topic: 'comida',
  difficulty: 'dificil',
  syllables: ['ro', 'sa'],
  syllableCount: 2,
),
WordModel(
  text: 'lampada',
  newLetter: 'm',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['lam', 'pa', 'da'],
  syllableCount: 3,
),
WordModel(
  text: 'poço',
  newLetter: 'c',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['po', 'ço'],
  syllableCount: 2,
  audioFileName: 'poco',
  imageFileName: 'poco',
),
WordModel(
  text: 'baloiço',
  newLetter: 'b',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['ba', 'loi', 'ço'],
  syllableCount: 3,
  audioFileName: 'baloico',
  imageFileName: 'baloico',
),
WordModel(
  text: 'pneu',
  newLetter: 'n',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['pneu'],
  syllableCount: 1,
),
WordModel(
  text: 'rampa',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['ram', 'pa'],
  syllableCount: 2,
),
WordModel(
  text: 'retângulo',
  newLetter: 'r',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['re', 'tân', 'gu', 'lo'],
  syllableCount: 4,
  audioFileName: 'retangulo',
  imageFileName: 'retangulo',
),
WordModel(
  text: 'comboio',
  newLetter: 'b',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['com', 'boi', 'o'],
  syllableCount: 3,
),
WordModel(
  text: 'bomba',
  newLetter: 'b',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['bom', 'ba'],
  syllableCount: 2,
),
WordModel(
  text: 'ambulância',
  newLetter: 'b',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['am', 'bu', 'lân', 'ci', 'a'],
  syllableCount: 5,
  audioFileName: 'ambulancia',
  imageFileName: 'ambulancia',
),
WordModel(
  text: 'tesoura',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['te', 'sou', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'losângulo',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['lo', 'sân', 'gu', 'lo'],
  syllableCount: 4,
  audioFileName: 'losangulo',
  imageFileName: 'losangulo',
),
WordModel(
  text: 'esfera',
  newLetter: 's',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['es', 'fe', 'ra'],
  syllableCount: 3,
),
WordModel(
  text: 'anzol',
  newLetter: 'z',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['an', 'zol'],
  syllableCount: 2,
),
WordModel(
  text: 'helicóptero',
  newLetter: 'h',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['he', 'li', 'cóp', 'te', 'ro'],
  syllableCount: 5,
  audioFileName: 'helicoptero',
  imageFileName: 'helicoptero',
),
WordModel(
  text: 'taxi',
  newLetter: 'x',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['ta', 'xi'],
  syllableCount: 2,
),
WordModel(
  text: 'cilindro',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['ci', 'lin', 'dro'],
  syllableCount: 3,
),
WordModel(
  text: 'esquadro',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['es', 'qua', 'dro'],
  syllableCount: 3,
),
WordModel(
  text: 'triângulo',
  newLetter: 'br, cr, dr, fr, gr, pr, tr, vr',
  topic: 'outros',
  difficulty: 'dificil',
  syllables: ['tri', 'ân', 'gu', 'lo'],
  syllableCount: 4,
  audioFileName: 'triangulo',
  imageFileName: 'triangulo',
),

];